package MARMSUI.SpecialisedSqlMappingToVo.model;

import java.util.Date;

public class CusClubQual extends CusClubQualKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String rcreUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.RCRE_DT
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date rcreDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String lchgUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.LCHG_DT
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date lchgDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_1
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_2
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_3
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_4
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_5
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_6
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_7
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_8
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_9
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.QUAL_DT_10
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Date qualDt10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_1
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_2
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_3
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_4
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_5
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_6
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_7
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_8
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_9
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_10
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tier10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.RCRE_USER_ID
     *
     * @return the value of CUS_CLUB_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.RCRE_USER_ID
     *
     * @param rcreUserId the value for CUS_CLUB_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.RCRE_DT
     *
     * @return the value of CUS_CLUB_QUAL.RCRE_DT
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.RCRE_DT
     *
     * @param rcreDt the value for CUS_CLUB_QUAL.RCRE_DT
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.LCHG_USER_ID
     *
     * @return the value of CUS_CLUB_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.LCHG_USER_ID
     *
     * @param lchgUserId the value for CUS_CLUB_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.LCHG_DT
     *
     * @return the value of CUS_CLUB_QUAL.LCHG_DT
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.LCHG_DT
     *
     * @param lchgDt the value for CUS_CLUB_QUAL.LCHG_DT
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_1
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_1
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt1() {
        return qualDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_1
     *
     * @param qualDt1 the value for CUS_CLUB_QUAL.QUAL_DT_1
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt1(Date qualDt1) {
        this.qualDt1 = qualDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_2
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_2
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt2() {
        return qualDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_2
     *
     * @param qualDt2 the value for CUS_CLUB_QUAL.QUAL_DT_2
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt2(Date qualDt2) {
        this.qualDt2 = qualDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_3
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_3
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt3() {
        return qualDt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_3
     *
     * @param qualDt3 the value for CUS_CLUB_QUAL.QUAL_DT_3
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt3(Date qualDt3) {
        this.qualDt3 = qualDt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_4
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_4
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt4() {
        return qualDt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_4
     *
     * @param qualDt4 the value for CUS_CLUB_QUAL.QUAL_DT_4
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt4(Date qualDt4) {
        this.qualDt4 = qualDt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_5
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_5
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt5() {
        return qualDt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_5
     *
     * @param qualDt5 the value for CUS_CLUB_QUAL.QUAL_DT_5
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt5(Date qualDt5) {
        this.qualDt5 = qualDt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_6
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_6
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt6() {
        return qualDt6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_6
     *
     * @param qualDt6 the value for CUS_CLUB_QUAL.QUAL_DT_6
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt6(Date qualDt6) {
        this.qualDt6 = qualDt6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_7
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_7
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt7() {
        return qualDt7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_7
     *
     * @param qualDt7 the value for CUS_CLUB_QUAL.QUAL_DT_7
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt7(Date qualDt7) {
        this.qualDt7 = qualDt7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_8
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_8
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt8() {
        return qualDt8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_8
     *
     * @param qualDt8 the value for CUS_CLUB_QUAL.QUAL_DT_8
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt8(Date qualDt8) {
        this.qualDt8 = qualDt8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_9
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_9
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt9() {
        return qualDt9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_9
     *
     * @param qualDt9 the value for CUS_CLUB_QUAL.QUAL_DT_9
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt9(Date qualDt9) {
        this.qualDt9 = qualDt9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.QUAL_DT_10
     *
     * @return the value of CUS_CLUB_QUAL.QUAL_DT_10
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Date getQualDt10() {
        return qualDt10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.QUAL_DT_10
     *
     * @param qualDt10 the value for CUS_CLUB_QUAL.QUAL_DT_10
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setQualDt10(Date qualDt10) {
        this.qualDt10 = qualDt10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_1
     *
     * @return the value of CUS_CLUB_QUAL.TIER_1
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier1() {
        return tier1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_1
     *
     * @param tier1 the value for CUS_CLUB_QUAL.TIER_1
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier1(String tier1) {
        this.tier1 = tier1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_2
     *
     * @return the value of CUS_CLUB_QUAL.TIER_2
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier2() {
        return tier2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_2
     *
     * @param tier2 the value for CUS_CLUB_QUAL.TIER_2
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier2(String tier2) {
        this.tier2 = tier2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_3
     *
     * @return the value of CUS_CLUB_QUAL.TIER_3
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier3() {
        return tier3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_3
     *
     * @param tier3 the value for CUS_CLUB_QUAL.TIER_3
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier3(String tier3) {
        this.tier3 = tier3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_4
     *
     * @return the value of CUS_CLUB_QUAL.TIER_4
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier4() {
        return tier4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_4
     *
     * @param tier4 the value for CUS_CLUB_QUAL.TIER_4
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier4(String tier4) {
        this.tier4 = tier4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_5
     *
     * @return the value of CUS_CLUB_QUAL.TIER_5
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier5() {
        return tier5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_5
     *
     * @param tier5 the value for CUS_CLUB_QUAL.TIER_5
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier5(String tier5) {
        this.tier5 = tier5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_6
     *
     * @return the value of CUS_CLUB_QUAL.TIER_6
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier6() {
        return tier6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_6
     *
     * @param tier6 the value for CUS_CLUB_QUAL.TIER_6
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier6(String tier6) {
        this.tier6 = tier6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_7
     *
     * @return the value of CUS_CLUB_QUAL.TIER_7
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier7() {
        return tier7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_7
     *
     * @param tier7 the value for CUS_CLUB_QUAL.TIER_7
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier7(String tier7) {
        this.tier7 = tier7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_8
     *
     * @return the value of CUS_CLUB_QUAL.TIER_8
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier8() {
        return tier8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_8
     *
     * @param tier8 the value for CUS_CLUB_QUAL.TIER_8
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier8(String tier8) {
        this.tier8 = tier8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_9
     *
     * @return the value of CUS_CLUB_QUAL.TIER_9
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier9() {
        return tier9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_9
     *
     * @param tier9 the value for CUS_CLUB_QUAL.TIER_9
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier9(String tier9) {
        this.tier9 = tier9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_10
     *
     * @return the value of CUS_CLUB_QUAL.TIER_10
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTier10() {
        return tier10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_10
     *
     * @param tier10 the value for CUS_CLUB_QUAL.TIER_10
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTier10(String tier10) {
        this.tier10 = tier10;
    }
}