package MARMSUI.SpecialisedSqlMappingToVo.model;

public class CusClubQualKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.INT_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private Long intId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.PRG_CD
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String prgCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_CLUB_QUAL.TIER_TYPE_IND
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    private String tierTypeInd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.INT_ID
     *
     * @return the value of CUS_CLUB_QUAL.INT_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.INT_ID
     *
     * @param intId the value for CUS_CLUB_QUAL.INT_ID
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.PRG_CD
     *
     * @return the value of CUS_CLUB_QUAL.PRG_CD
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getPrgCd() {
        return prgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.PRG_CD
     *
     * @param prgCd the value for CUS_CLUB_QUAL.PRG_CD
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setPrgCd(String prgCd) {
        this.prgCd = prgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_CLUB_QUAL.TIER_TYPE_IND
     *
     * @return the value of CUS_CLUB_QUAL.TIER_TYPE_IND
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public String getTierTypeInd() {
        return tierTypeInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_CLUB_QUAL.TIER_TYPE_IND
     *
     * @param tierTypeInd the value for CUS_CLUB_QUAL.TIER_TYPE_IND
     *
     * @mbg.generated Wed Nov 29 13:01:35 SGT 2023
     */
    public void setTierTypeInd(String tierTypeInd) {
        this.tierTypeInd = tierTypeInd;
    }
}