package MARMSUI.SpecialisedSqlMappingToVo.model;

import java.math.BigDecimal;
import java.util.Date;

public class CusPpsQual extends CusPpsQualKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String rcreUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.RCRE_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date rcreDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String lchgUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.LCHG_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date lchgDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.TIER_STATUS_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String tierStatusInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.QLFY_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String qlfyInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.QLFY_START_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date qlfyStartDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Long curMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.CUR_SECT_CNT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private BigDecimal curSectCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.NO_YRS_QLYFIED
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Short noYrsQlyfied;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.QLFY_END_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date qlfyEndDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.FORCE_QLFY_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date forceQlfyDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date forceQlfyExtendedDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.NO_OF_EXTENDED_MTH
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Short noOfExtendedMth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.ORIG_EXP
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date origExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.QLFD_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date qlfdDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date tierBonusAwardStartDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Date tierBonusAwardEndDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.YRS_IN_QPP
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Short yrsInQpp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.CUR_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Long curVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.AUTO_REQUAL_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String autoRequalInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.HV_FLG
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String hvFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.QUAL_SCHEME
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String qualScheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Short consecutiveYrsQualified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.NA_CUR_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Long naCurVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.NA_RWD_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Long naRwdVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.RCRE_USER_ID
     *
     * @return the value of CUS_PPS_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.RCRE_USER_ID
     *
     * @param rcreUserId the value for CUS_PPS_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.RCRE_DT
     *
     * @return the value of CUS_PPS_QUAL.RCRE_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.RCRE_DT
     *
     * @param rcreDt the value for CUS_PPS_QUAL.RCRE_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.LCHG_USER_ID
     *
     * @return the value of CUS_PPS_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.LCHG_USER_ID
     *
     * @param lchgUserId the value for CUS_PPS_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.LCHG_DT
     *
     * @return the value of CUS_PPS_QUAL.LCHG_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.LCHG_DT
     *
     * @param lchgDt the value for CUS_PPS_QUAL.LCHG_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.TIER_STATUS_IND
     *
     * @return the value of CUS_PPS_QUAL.TIER_STATUS_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getTierStatusInd() {
        return tierStatusInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.TIER_STATUS_IND
     *
     * @param tierStatusInd the value for CUS_PPS_QUAL.TIER_STATUS_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setTierStatusInd(String tierStatusInd) {
        this.tierStatusInd = tierStatusInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.QLFY_IND
     *
     * @return the value of CUS_PPS_QUAL.QLFY_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getQlfyInd() {
        return qlfyInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.QLFY_IND
     *
     * @param qlfyInd the value for CUS_PPS_QUAL.QLFY_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setQlfyInd(String qlfyInd) {
        this.qlfyInd = qlfyInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.QLFY_START_DT
     *
     * @return the value of CUS_PPS_QUAL.QLFY_START_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getQlfyStartDt() {
        return qlfyStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.QLFY_START_DT
     *
     * @param qlfyStartDt the value for CUS_PPS_QUAL.QLFY_START_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setQlfyStartDt(Date qlfyStartDt) {
        this.qlfyStartDt = qlfyStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.CUR_MILEAGE
     *
     * @return the value of CUS_PPS_QUAL.CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Long getCurMileage() {
        return curMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.CUR_MILEAGE
     *
     * @param curMileage the value for CUS_PPS_QUAL.CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setCurMileage(Long curMileage) {
        this.curMileage = curMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.CUR_SECT_CNT
     *
     * @return the value of CUS_PPS_QUAL.CUR_SECT_CNT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public BigDecimal getCurSectCnt() {
        return curSectCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.CUR_SECT_CNT
     *
     * @param curSectCnt the value for CUS_PPS_QUAL.CUR_SECT_CNT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setCurSectCnt(BigDecimal curSectCnt) {
        this.curSectCnt = curSectCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.NO_YRS_QLYFIED
     *
     * @return the value of CUS_PPS_QUAL.NO_YRS_QLYFIED
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Short getNoYrsQlyfied() {
        return noYrsQlyfied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.NO_YRS_QLYFIED
     *
     * @param noYrsQlyfied the value for CUS_PPS_QUAL.NO_YRS_QLYFIED
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setNoYrsQlyfied(Short noYrsQlyfied) {
        this.noYrsQlyfied = noYrsQlyfied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.QLFY_END_DT
     *
     * @return the value of CUS_PPS_QUAL.QLFY_END_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getQlfyEndDt() {
        return qlfyEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.QLFY_END_DT
     *
     * @param qlfyEndDt the value for CUS_PPS_QUAL.QLFY_END_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setQlfyEndDt(Date qlfyEndDt) {
        this.qlfyEndDt = qlfyEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.FORCE_QLFY_DT
     *
     * @return the value of CUS_PPS_QUAL.FORCE_QLFY_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getForceQlfyDt() {
        return forceQlfyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.FORCE_QLFY_DT
     *
     * @param forceQlfyDt the value for CUS_PPS_QUAL.FORCE_QLFY_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setForceQlfyDt(Date forceQlfyDt) {
        this.forceQlfyDt = forceQlfyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @return the value of CUS_PPS_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getForceQlfyExtendedDt() {
        return forceQlfyExtendedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @param forceQlfyExtendedDt the value for CUS_PPS_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setForceQlfyExtendedDt(Date forceQlfyExtendedDt) {
        this.forceQlfyExtendedDt = forceQlfyExtendedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.NO_OF_EXTENDED_MTH
     *
     * @return the value of CUS_PPS_QUAL.NO_OF_EXTENDED_MTH
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Short getNoOfExtendedMth() {
        return noOfExtendedMth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.NO_OF_EXTENDED_MTH
     *
     * @param noOfExtendedMth the value for CUS_PPS_QUAL.NO_OF_EXTENDED_MTH
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setNoOfExtendedMth(Short noOfExtendedMth) {
        this.noOfExtendedMth = noOfExtendedMth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.ORIG_EXP
     *
     * @return the value of CUS_PPS_QUAL.ORIG_EXP
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getOrigExp() {
        return origExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.ORIG_EXP
     *
     * @param origExp the value for CUS_PPS_QUAL.ORIG_EXP
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setOrigExp(Date origExp) {
        this.origExp = origExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.QLFD_DT
     *
     * @return the value of CUS_PPS_QUAL.QLFD_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getQlfdDt() {
        return qlfdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.QLFD_DT
     *
     * @param qlfdDt the value for CUS_PPS_QUAL.QLFD_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setQlfdDt(Date qlfdDt) {
        this.qlfdDt = qlfdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @return the value of CUS_PPS_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getTierBonusAwardStartDt() {
        return tierBonusAwardStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @param tierBonusAwardStartDt the value for CUS_PPS_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setTierBonusAwardStartDt(Date tierBonusAwardStartDt) {
        this.tierBonusAwardStartDt = tierBonusAwardStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @return the value of CUS_PPS_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Date getTierBonusAwardEndDt() {
        return tierBonusAwardEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @param tierBonusAwardEndDt the value for CUS_PPS_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setTierBonusAwardEndDt(Date tierBonusAwardEndDt) {
        this.tierBonusAwardEndDt = tierBonusAwardEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.YRS_IN_QPP
     *
     * @return the value of CUS_PPS_QUAL.YRS_IN_QPP
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Short getYrsInQpp() {
        return yrsInQpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.YRS_IN_QPP
     *
     * @param yrsInQpp the value for CUS_PPS_QUAL.YRS_IN_QPP
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setYrsInQpp(Short yrsInQpp) {
        this.yrsInQpp = yrsInQpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.CUR_VAL
     *
     * @return the value of CUS_PPS_QUAL.CUR_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Long getCurVal() {
        return curVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.CUR_VAL
     *
     * @param curVal the value for CUS_PPS_QUAL.CUR_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setCurVal(Long curVal) {
        this.curVal = curVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.AUTO_REQUAL_IND
     *
     * @return the value of CUS_PPS_QUAL.AUTO_REQUAL_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getAutoRequalInd() {
        return autoRequalInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.AUTO_REQUAL_IND
     *
     * @param autoRequalInd the value for CUS_PPS_QUAL.AUTO_REQUAL_IND
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setAutoRequalInd(String autoRequalInd) {
        this.autoRequalInd = autoRequalInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.HV_FLG
     *
     * @return the value of CUS_PPS_QUAL.HV_FLG
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getHvFlg() {
        return hvFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.HV_FLG
     *
     * @param hvFlg the value for CUS_PPS_QUAL.HV_FLG
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setHvFlg(String hvFlg) {
        this.hvFlg = hvFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.QUAL_SCHEME
     *
     * @return the value of CUS_PPS_QUAL.QUAL_SCHEME
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getQualScheme() {
        return qualScheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.QUAL_SCHEME
     *
     * @param qualScheme the value for CUS_PPS_QUAL.QUAL_SCHEME
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setQualScheme(String qualScheme) {
        this.qualScheme = qualScheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @return the value of CUS_PPS_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Short getConsecutiveYrsQualified() {
        return consecutiveYrsQualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @param consecutiveYrsQualified the value for CUS_PPS_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setConsecutiveYrsQualified(Short consecutiveYrsQualified) {
        this.consecutiveYrsQualified = consecutiveYrsQualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.NA_CUR_VAL
     *
     * @return the value of CUS_PPS_QUAL.NA_CUR_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Long getNaCurVal() {
        return naCurVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.NA_CUR_VAL
     *
     * @param naCurVal the value for CUS_PPS_QUAL.NA_CUR_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setNaCurVal(Long naCurVal) {
        this.naCurVal = naCurVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.NA_RWD_VAL
     *
     * @return the value of CUS_PPS_QUAL.NA_RWD_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Long getNaRwdVal() {
        return naRwdVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.NA_RWD_VAL
     *
     * @param naRwdVal the value for CUS_PPS_QUAL.NA_RWD_VAL
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setNaRwdVal(Long naRwdVal) {
        this.naRwdVal = naRwdVal;
    }
}