package MARMSUI.SpecialisedSqlMappingToVo.model;

public class CusPpsQualKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.INT_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private Long intId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PPS_QUAL.PRG_CD
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    private String prgCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.INT_ID
     *
     * @return the value of CUS_PPS_QUAL.INT_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.INT_ID
     *
     * @param intId the value for CUS_PPS_QUAL.INT_ID
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PPS_QUAL.PRG_CD
     *
     * @return the value of CUS_PPS_QUAL.PRG_CD
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public String getPrgCd() {
        return prgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PPS_QUAL.PRG_CD
     *
     * @param prgCd the value for CUS_PPS_QUAL.PRG_CD
     *
     * @mbg.generated Thu Nov 30 13:42:48 SGT 2023
     */
    public void setPrgCd(String prgCd) {
        this.prgCd = prgCd;
    }
}