package MARMSUI.SpecialisedSqlMappingToVo.model;

import java.util.Date;

public class HisCusEliteQual {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private String rcreUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.RCRE_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date rcreDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private String lchgUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.LCHG_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date lchgDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.INT_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Long intId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.PRG_CD
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private String prgCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.TIER_STATUS_IND
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private String tierStatusInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.QLFY_IND
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private String qlfyInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.QLFY_START_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date qlfyStartDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Long curMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.NO_YRS_QLFD
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Short noYrsQlfd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.QLFY_END_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date qlfyEndDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.FORCE_QLFY_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date forceQlfyDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date forceQlfyExtendedDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.NO_OF_EXTENDED_MTH
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Short noOfExtendedMth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.ORIG_EXP
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date origExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.QLFD_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date qlfdDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.TIER_EXP
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date tierExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date tierBonusAwardStartDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Date tierBonusAwardEndDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.DISCTRY_TIER_FLG
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private String disctryTierFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Short consecutiveYrsQualified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.NA_CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Long naCurMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HIS_CUS_ELITE_QUAL.NA_KFMR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    private Long naKfmrMileage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.RCRE_USER_ID
     *
     * @return the value of HIS_CUS_ELITE_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.RCRE_USER_ID
     *
     * @param rcreUserId the value for HIS_CUS_ELITE_QUAL.RCRE_USER_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.RCRE_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.RCRE_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.RCRE_DT
     *
     * @param rcreDt the value for HIS_CUS_ELITE_QUAL.RCRE_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.LCHG_USER_ID
     *
     * @return the value of HIS_CUS_ELITE_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.LCHG_USER_ID
     *
     * @param lchgUserId the value for HIS_CUS_ELITE_QUAL.LCHG_USER_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.LCHG_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.LCHG_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.LCHG_DT
     *
     * @param lchgDt the value for HIS_CUS_ELITE_QUAL.LCHG_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.INT_ID
     *
     * @return the value of HIS_CUS_ELITE_QUAL.INT_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.INT_ID
     *
     * @param intId the value for HIS_CUS_ELITE_QUAL.INT_ID
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.PRG_CD
     *
     * @return the value of HIS_CUS_ELITE_QUAL.PRG_CD
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public String getPrgCd() {
        return prgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.PRG_CD
     *
     * @param prgCd the value for HIS_CUS_ELITE_QUAL.PRG_CD
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setPrgCd(String prgCd) {
        this.prgCd = prgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.TIER_STATUS_IND
     *
     * @return the value of HIS_CUS_ELITE_QUAL.TIER_STATUS_IND
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public String getTierStatusInd() {
        return tierStatusInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.TIER_STATUS_IND
     *
     * @param tierStatusInd the value for HIS_CUS_ELITE_QUAL.TIER_STATUS_IND
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setTierStatusInd(String tierStatusInd) {
        this.tierStatusInd = tierStatusInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.QLFY_IND
     *
     * @return the value of HIS_CUS_ELITE_QUAL.QLFY_IND
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public String getQlfyInd() {
        return qlfyInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.QLFY_IND
     *
     * @param qlfyInd the value for HIS_CUS_ELITE_QUAL.QLFY_IND
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setQlfyInd(String qlfyInd) {
        this.qlfyInd = qlfyInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.QLFY_START_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.QLFY_START_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getQlfyStartDt() {
        return qlfyStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.QLFY_START_DT
     *
     * @param qlfyStartDt the value for HIS_CUS_ELITE_QUAL.QLFY_START_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setQlfyStartDt(Date qlfyStartDt) {
        this.qlfyStartDt = qlfyStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.CUR_MILEAGE
     *
     * @return the value of HIS_CUS_ELITE_QUAL.CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Long getCurMileage() {
        return curMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.CUR_MILEAGE
     *
     * @param curMileage the value for HIS_CUS_ELITE_QUAL.CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setCurMileage(Long curMileage) {
        this.curMileage = curMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.NO_YRS_QLFD
     *
     * @return the value of HIS_CUS_ELITE_QUAL.NO_YRS_QLFD
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Short getNoYrsQlfd() {
        return noYrsQlfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.NO_YRS_QLFD
     *
     * @param noYrsQlfd the value for HIS_CUS_ELITE_QUAL.NO_YRS_QLFD
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setNoYrsQlfd(Short noYrsQlfd) {
        this.noYrsQlfd = noYrsQlfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.QLFY_END_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.QLFY_END_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getQlfyEndDt() {
        return qlfyEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.QLFY_END_DT
     *
     * @param qlfyEndDt the value for HIS_CUS_ELITE_QUAL.QLFY_END_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setQlfyEndDt(Date qlfyEndDt) {
        this.qlfyEndDt = qlfyEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.FORCE_QLFY_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.FORCE_QLFY_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getForceQlfyDt() {
        return forceQlfyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.FORCE_QLFY_DT
     *
     * @param forceQlfyDt the value for HIS_CUS_ELITE_QUAL.FORCE_QLFY_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setForceQlfyDt(Date forceQlfyDt) {
        this.forceQlfyDt = forceQlfyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getForceQlfyExtendedDt() {
        return forceQlfyExtendedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @param forceQlfyExtendedDt the value for HIS_CUS_ELITE_QUAL.FORCE_QLFY_EXTENDED_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setForceQlfyExtendedDt(Date forceQlfyExtendedDt) {
        this.forceQlfyExtendedDt = forceQlfyExtendedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.NO_OF_EXTENDED_MTH
     *
     * @return the value of HIS_CUS_ELITE_QUAL.NO_OF_EXTENDED_MTH
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Short getNoOfExtendedMth() {
        return noOfExtendedMth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.NO_OF_EXTENDED_MTH
     *
     * @param noOfExtendedMth the value for HIS_CUS_ELITE_QUAL.NO_OF_EXTENDED_MTH
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setNoOfExtendedMth(Short noOfExtendedMth) {
        this.noOfExtendedMth = noOfExtendedMth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.ORIG_EXP
     *
     * @return the value of HIS_CUS_ELITE_QUAL.ORIG_EXP
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getOrigExp() {
        return origExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.ORIG_EXP
     *
     * @param origExp the value for HIS_CUS_ELITE_QUAL.ORIG_EXP
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setOrigExp(Date origExp) {
        this.origExp = origExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.QLFD_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.QLFD_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getQlfdDt() {
        return qlfdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.QLFD_DT
     *
     * @param qlfdDt the value for HIS_CUS_ELITE_QUAL.QLFD_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setQlfdDt(Date qlfdDt) {
        this.qlfdDt = qlfdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.TIER_EXP
     *
     * @return the value of HIS_CUS_ELITE_QUAL.TIER_EXP
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getTierExp() {
        return tierExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.TIER_EXP
     *
     * @param tierExp the value for HIS_CUS_ELITE_QUAL.TIER_EXP
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setTierExp(Date tierExp) {
        this.tierExp = tierExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getTierBonusAwardStartDt() {
        return tierBonusAwardStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @param tierBonusAwardStartDt the value for HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_START_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setTierBonusAwardStartDt(Date tierBonusAwardStartDt) {
        this.tierBonusAwardStartDt = tierBonusAwardStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @return the value of HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Date getTierBonusAwardEndDt() {
        return tierBonusAwardEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @param tierBonusAwardEndDt the value for HIS_CUS_ELITE_QUAL.TIER_BONUS_AWARD_END_DT
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setTierBonusAwardEndDt(Date tierBonusAwardEndDt) {
        this.tierBonusAwardEndDt = tierBonusAwardEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.DISCTRY_TIER_FLG
     *
     * @return the value of HIS_CUS_ELITE_QUAL.DISCTRY_TIER_FLG
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public String getDisctryTierFlg() {
        return disctryTierFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.DISCTRY_TIER_FLG
     *
     * @param disctryTierFlg the value for HIS_CUS_ELITE_QUAL.DISCTRY_TIER_FLG
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setDisctryTierFlg(String disctryTierFlg) {
        this.disctryTierFlg = disctryTierFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @return the value of HIS_CUS_ELITE_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Short getConsecutiveYrsQualified() {
        return consecutiveYrsQualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @param consecutiveYrsQualified the value for HIS_CUS_ELITE_QUAL.CONSECUTIVE_YRS_QUALIFIED
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setConsecutiveYrsQualified(Short consecutiveYrsQualified) {
        this.consecutiveYrsQualified = consecutiveYrsQualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.NA_CUR_MILEAGE
     *
     * @return the value of HIS_CUS_ELITE_QUAL.NA_CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Long getNaCurMileage() {
        return naCurMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.NA_CUR_MILEAGE
     *
     * @param naCurMileage the value for HIS_CUS_ELITE_QUAL.NA_CUR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setNaCurMileage(Long naCurMileage) {
        this.naCurMileage = naCurMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HIS_CUS_ELITE_QUAL.NA_KFMR_MILEAGE
     *
     * @return the value of HIS_CUS_ELITE_QUAL.NA_KFMR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public Long getNaKfmrMileage() {
        return naKfmrMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HIS_CUS_ELITE_QUAL.NA_KFMR_MILEAGE
     *
     * @param naKfmrMileage the value for HIS_CUS_ELITE_QUAL.NA_KFMR_MILEAGE
     *
     * @mbg.generated Thu Nov 30 10:45:37 SGT 2023
     */
    public void setNaKfmrMileage(Long naKfmrMileage) {
        this.naKfmrMileage = naKfmrMileage;
    }
}