/* 
* =============================================================================== 
* For internal use of Singapore Airlines and TATA Consultancy Services only. 
* (C) 2019 Singapore Airlines. 
* Singapore Co. Reg. No. 197200078R. All Rights Reserved. 
* 
* Information in this file is the intellectual property of SINGAPORE AIRLINES. 
* =============================================================================== 
*/

package MARMSUI.migration.model;

import java.util.Date;

public class AircraftType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.AIRCRAFT_TYPE_CD
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String aircraftTypeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.RCRE_USER_ID
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String rcreUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.RCRE_DT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Date rcreDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.LCHG_USER_ID
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String lchgUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.LCHG_DT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Date lchgDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.AIRCRAFT_TYPE_DESC
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String aircraftTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.P_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String pClsSeatAlphaRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short pClsSeatNoRangeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short pClsSeatNoRangeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.J_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String jClsSeatAlphaRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short jClsSeatNoRangeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short jClsSeatNoRangeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.Y_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String yClsSeatAlphaRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short yClsSeatNoRangeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short yClsSeatNoRangeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.P_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short pClassSeatCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.J_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short jClassSeatCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.Y_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short yClassSeatCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.ALTEA_AIRCRAFTTYPE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String alteaAircrafttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.S_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private String sClsSeatAlphaRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short sClsSeatNoRangeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short sClsSeatNoRangeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIRCRAFT_TYPE.S_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    private Short sClassSeatCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.AIRCRAFT_TYPE_CD
     *
     * @return the value of AIRCRAFT_TYPE.AIRCRAFT_TYPE_CD
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getAircraftTypeCd() {
        return aircraftTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.AIRCRAFT_TYPE_CD
     *
     * @param aircraftTypeCd the value for AIRCRAFT_TYPE.AIRCRAFT_TYPE_CD
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setAircraftTypeCd(String aircraftTypeCd) {
        this.aircraftTypeCd = aircraftTypeCd == null ? null : aircraftTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.RCRE_USER_ID
     *
     * @return the value of AIRCRAFT_TYPE.RCRE_USER_ID
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.RCRE_USER_ID
     *
     * @param rcreUserId the value for AIRCRAFT_TYPE.RCRE_USER_ID
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId == null ? null : rcreUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.RCRE_DT
     *
     * @return the value of AIRCRAFT_TYPE.RCRE_DT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.RCRE_DT
     *
     * @param rcreDt the value for AIRCRAFT_TYPE.RCRE_DT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.LCHG_USER_ID
     *
     * @return the value of AIRCRAFT_TYPE.LCHG_USER_ID
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.LCHG_USER_ID
     *
     * @param lchgUserId the value for AIRCRAFT_TYPE.LCHG_USER_ID
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId == null ? null : lchgUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.LCHG_DT
     *
     * @return the value of AIRCRAFT_TYPE.LCHG_DT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.LCHG_DT
     *
     * @param lchgDt the value for AIRCRAFT_TYPE.LCHG_DT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.AIRCRAFT_TYPE_DESC
     *
     * @return the value of AIRCRAFT_TYPE.AIRCRAFT_TYPE_DESC
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getAircraftTypeDesc() {
        return aircraftTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.AIRCRAFT_TYPE_DESC
     *
     * @param aircraftTypeDesc the value for AIRCRAFT_TYPE.AIRCRAFT_TYPE_DESC
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setAircraftTypeDesc(String aircraftTypeDesc) {
        this.aircraftTypeDesc = aircraftTypeDesc == null ? null : aircraftTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.P_CLS_SEAT_ALPHA_RANGE
     *
     * @return the value of AIRCRAFT_TYPE.P_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getpClsSeatAlphaRange() {
        return pClsSeatAlphaRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.P_CLS_SEAT_ALPHA_RANGE
     *
     * @param pClsSeatAlphaRange the value for AIRCRAFT_TYPE.P_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setpClsSeatAlphaRange(String pClsSeatAlphaRange) {
        this.pClsSeatAlphaRange = pClsSeatAlphaRange == null ? null : pClsSeatAlphaRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_START
     *
     * @return the value of AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getpClsSeatNoRangeStart() {
        return pClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_START
     *
     * @param pClsSeatNoRangeStart the value for AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setpClsSeatNoRangeStart(Short pClsSeatNoRangeStart) {
        this.pClsSeatNoRangeStart = pClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_END
     *
     * @return the value of AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getpClsSeatNoRangeEnd() {
        return pClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_END
     *
     * @param pClsSeatNoRangeEnd the value for AIRCRAFT_TYPE.P_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setpClsSeatNoRangeEnd(Short pClsSeatNoRangeEnd) {
        this.pClsSeatNoRangeEnd = pClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.J_CLS_SEAT_ALPHA_RANGE
     *
     * @return the value of AIRCRAFT_TYPE.J_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getjClsSeatAlphaRange() {
        return jClsSeatAlphaRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.J_CLS_SEAT_ALPHA_RANGE
     *
     * @param jClsSeatAlphaRange the value for AIRCRAFT_TYPE.J_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setjClsSeatAlphaRange(String jClsSeatAlphaRange) {
        this.jClsSeatAlphaRange = jClsSeatAlphaRange == null ? null : jClsSeatAlphaRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_START
     *
     * @return the value of AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getjClsSeatNoRangeStart() {
        return jClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_START
     *
     * @param jClsSeatNoRangeStart the value for AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setjClsSeatNoRangeStart(Short jClsSeatNoRangeStart) {
        this.jClsSeatNoRangeStart = jClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_END
     *
     * @return the value of AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getjClsSeatNoRangeEnd() {
        return jClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_END
     *
     * @param jClsSeatNoRangeEnd the value for AIRCRAFT_TYPE.J_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setjClsSeatNoRangeEnd(Short jClsSeatNoRangeEnd) {
        this.jClsSeatNoRangeEnd = jClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.Y_CLS_SEAT_ALPHA_RANGE
     *
     * @return the value of AIRCRAFT_TYPE.Y_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getyClsSeatAlphaRange() {
        return yClsSeatAlphaRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.Y_CLS_SEAT_ALPHA_RANGE
     *
     * @param yClsSeatAlphaRange the value for AIRCRAFT_TYPE.Y_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setyClsSeatAlphaRange(String yClsSeatAlphaRange) {
        this.yClsSeatAlphaRange = yClsSeatAlphaRange == null ? null : yClsSeatAlphaRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_START
     *
     * @return the value of AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getyClsSeatNoRangeStart() {
        return yClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_START
     *
     * @param yClsSeatNoRangeStart the value for AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setyClsSeatNoRangeStart(Short yClsSeatNoRangeStart) {
        this.yClsSeatNoRangeStart = yClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_END
     *
     * @return the value of AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getyClsSeatNoRangeEnd() {
        return yClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_END
     *
     * @param yClsSeatNoRangeEnd the value for AIRCRAFT_TYPE.Y_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setyClsSeatNoRangeEnd(Short yClsSeatNoRangeEnd) {
        this.yClsSeatNoRangeEnd = yClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.P_CLASS_SEAT_COUNT
     *
     * @return the value of AIRCRAFT_TYPE.P_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getpClassSeatCount() {
        return pClassSeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.P_CLASS_SEAT_COUNT
     *
     * @param pClassSeatCount the value for AIRCRAFT_TYPE.P_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setpClassSeatCount(Short pClassSeatCount) {
        this.pClassSeatCount = pClassSeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.J_CLASS_SEAT_COUNT
     *
     * @return the value of AIRCRAFT_TYPE.J_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getjClassSeatCount() {
        return jClassSeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.J_CLASS_SEAT_COUNT
     *
     * @param jClassSeatCount the value for AIRCRAFT_TYPE.J_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setjClassSeatCount(Short jClassSeatCount) {
        this.jClassSeatCount = jClassSeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.Y_CLASS_SEAT_COUNT
     *
     * @return the value of AIRCRAFT_TYPE.Y_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getyClassSeatCount() {
        return yClassSeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.Y_CLASS_SEAT_COUNT
     *
     * @param yClassSeatCount the value for AIRCRAFT_TYPE.Y_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setyClassSeatCount(Short yClassSeatCount) {
        this.yClassSeatCount = yClassSeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.ALTEA_AIRCRAFTTYPE
     *
     * @return the value of AIRCRAFT_TYPE.ALTEA_AIRCRAFTTYPE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getAlteaAircrafttype() {
        return alteaAircrafttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.ALTEA_AIRCRAFTTYPE
     *
     * @param alteaAircrafttype the value for AIRCRAFT_TYPE.ALTEA_AIRCRAFTTYPE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setAlteaAircrafttype(String alteaAircrafttype) {
        this.alteaAircrafttype = alteaAircrafttype == null ? null : alteaAircrafttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.S_CLS_SEAT_ALPHA_RANGE
     *
     * @return the value of AIRCRAFT_TYPE.S_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public String getsClsSeatAlphaRange() {
        return sClsSeatAlphaRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.S_CLS_SEAT_ALPHA_RANGE
     *
     * @param sClsSeatAlphaRange the value for AIRCRAFT_TYPE.S_CLS_SEAT_ALPHA_RANGE
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setsClsSeatAlphaRange(String sClsSeatAlphaRange) {
        this.sClsSeatAlphaRange = sClsSeatAlphaRange == null ? null : sClsSeatAlphaRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_START
     *
     * @return the value of AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getsClsSeatNoRangeStart() {
        return sClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_START
     *
     * @param sClsSeatNoRangeStart the value for AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_START
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setsClsSeatNoRangeStart(Short sClsSeatNoRangeStart) {
        this.sClsSeatNoRangeStart = sClsSeatNoRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_END
     *
     * @return the value of AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getsClsSeatNoRangeEnd() {
        return sClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_END
     *
     * @param sClsSeatNoRangeEnd the value for AIRCRAFT_TYPE.S_CLS_SEAT_NO_RANGE_END
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setsClsSeatNoRangeEnd(Short sClsSeatNoRangeEnd) {
        this.sClsSeatNoRangeEnd = sClsSeatNoRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIRCRAFT_TYPE.S_CLASS_SEAT_COUNT
     *
     * @return the value of AIRCRAFT_TYPE.S_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public Short getsClassSeatCount() {
        return sClassSeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIRCRAFT_TYPE.S_CLASS_SEAT_COUNT
     *
     * @param sClassSeatCount the value for AIRCRAFT_TYPE.S_CLASS_SEAT_COUNT
     *
     * @mbggenerated Thu Oct 25 11:01:37 IST 2018
     */
    public void setsClassSeatCount(Short sClassSeatCount) {
        this.sClassSeatCount = sClassSeatCount;
    }
}