/* 
* =============================================================================== 
* For internal use of Singapore Airlines and TATA Consultancy Services only. 
* (C) 2019 Singapore Airlines. 
* Singapore Co. Reg. No. 197200078R. All Rights Reserved. 
* 
* Information in this file is the intellectual property of SINGAPORE AIRLINES. 
* =============================================================================== 
*/

package MARMSUI.migration.model;

import java.util.Date;

public class CusAccount implements java.io.Serializable{
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.RCRE_USER_ID
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String rcreUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.RCRE_DT
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private Date rcreDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.LCHG_USER_ID
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String lchgUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.LCHG_DT
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private Date lchgDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.INT_ID
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private Long intId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.PRG_CD
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String prgCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.CUS_ID
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String cusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.ACCT_STATUS_IND
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String acctStatusInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.ACCT_STATUS_CHG_DT
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private Date acctStatusChgDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.ACCT_STATUS_RSN_CD
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String acctStatusRsnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.ACCT_STATUS_RSN_DESC
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String acctStatusRsnDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.TIER_STATUS_IND
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String tierStatusInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.TIER_STATUS_CHG_DT
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private Date tierStatusChgDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.IS_YEC_FLG
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String isYecFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.CARD_VALID_TILL_DT
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private Date cardValidTillDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.IGNORE_FLG
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String ignoreFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.LAST_ACT_DT
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private Date lastActDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.HV_FLG
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String hvFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.ACV_VALUE
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String acvValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.AIRLINE_TIER
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String airlineTier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_ACCOUNT.ACV_OVERRIDE_FLG
     *
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    private String acvOverrideFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.RCRE_USER_ID
     *
     * @return the value of CUS_ACCOUNT.RCRE_USER_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.RCRE_USER_ID
     *
     * @param rcreUserId the value for CUS_ACCOUNT.RCRE_USER_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId == null ? null : rcreUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.RCRE_DT
     *
     * @return the value of CUS_ACCOUNT.RCRE_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.RCRE_DT
     *
     * @param rcreDt the value for CUS_ACCOUNT.RCRE_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.LCHG_USER_ID
     *
     * @return the value of CUS_ACCOUNT.LCHG_USER_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.LCHG_USER_ID
     *
     * @param lchgUserId the value for CUS_ACCOUNT.LCHG_USER_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId == null ? null : lchgUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.LCHG_DT
     *
     * @return the value of CUS_ACCOUNT.LCHG_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.LCHG_DT
     *
     * @param lchgDt the value for CUS_ACCOUNT.LCHG_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.INT_ID
     *
     * @return the value of CUS_ACCOUNT.INT_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.INT_ID
     *
     * @param intId the value for CUS_ACCOUNT.INT_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.PRG_CD
     *
     * @return the value of CUS_ACCOUNT.PRG_CD
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getPrgCd() {
        return prgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.PRG_CD
     *
     * @param prgCd the value for CUS_ACCOUNT.PRG_CD
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setPrgCd(String prgCd) {
        this.prgCd = prgCd == null ? null : prgCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.CUS_ID
     *
     * @return the value of CUS_ACCOUNT.CUS_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getCusId() {
        return cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.CUS_ID
     *
     * @param cusId the value for CUS_ACCOUNT.CUS_ID
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setCusId(String cusId) {
        this.cusId = cusId == null ? null : cusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.ACCT_STATUS_IND
     *
     * @return the value of CUS_ACCOUNT.ACCT_STATUS_IND
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getAcctStatusInd() {
        return acctStatusInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.ACCT_STATUS_IND
     *
     * @param acctStatusInd the value for CUS_ACCOUNT.ACCT_STATUS_IND
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setAcctStatusInd(String acctStatusInd) {
        this.acctStatusInd = acctStatusInd == null ? null : acctStatusInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.ACCT_STATUS_CHG_DT
     *
     * @return the value of CUS_ACCOUNT.ACCT_STATUS_CHG_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public Date getAcctStatusChgDt() {
        return acctStatusChgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.ACCT_STATUS_CHG_DT
     *
     * @param acctStatusChgDt the value for CUS_ACCOUNT.ACCT_STATUS_CHG_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setAcctStatusChgDt(Date acctStatusChgDt) {
        this.acctStatusChgDt = acctStatusChgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.ACCT_STATUS_RSN_CD
     *
     * @return the value of CUS_ACCOUNT.ACCT_STATUS_RSN_CD
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getAcctStatusRsnCd() {
        return acctStatusRsnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.ACCT_STATUS_RSN_CD
     *
     * @param acctStatusRsnCd the value for CUS_ACCOUNT.ACCT_STATUS_RSN_CD
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setAcctStatusRsnCd(String acctStatusRsnCd) {
        this.acctStatusRsnCd = acctStatusRsnCd == null ? null : acctStatusRsnCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.ACCT_STATUS_RSN_DESC
     *
     * @return the value of CUS_ACCOUNT.ACCT_STATUS_RSN_DESC
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getAcctStatusRsnDesc() {
        return acctStatusRsnDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.ACCT_STATUS_RSN_DESC
     *
     * @param acctStatusRsnDesc the value for CUS_ACCOUNT.ACCT_STATUS_RSN_DESC
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setAcctStatusRsnDesc(String acctStatusRsnDesc) {
        this.acctStatusRsnDesc = acctStatusRsnDesc == null ? null : acctStatusRsnDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.TIER_STATUS_IND
     *
     * @return the value of CUS_ACCOUNT.TIER_STATUS_IND
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getTierStatusInd() {
        return tierStatusInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.TIER_STATUS_IND
     *
     * @param tierStatusInd the value for CUS_ACCOUNT.TIER_STATUS_IND
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setTierStatusInd(String tierStatusInd) {
        this.tierStatusInd = tierStatusInd == null ? null : tierStatusInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.TIER_STATUS_CHG_DT
     *
     * @return the value of CUS_ACCOUNT.TIER_STATUS_CHG_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public Date getTierStatusChgDt() {
        return tierStatusChgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.TIER_STATUS_CHG_DT
     *
     * @param tierStatusChgDt the value for CUS_ACCOUNT.TIER_STATUS_CHG_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setTierStatusChgDt(Date tierStatusChgDt) {
        this.tierStatusChgDt = tierStatusChgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.IS_YEC_FLG
     *
     * @return the value of CUS_ACCOUNT.IS_YEC_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getIsYecFlg() {
        return isYecFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.IS_YEC_FLG
     *
     * @param isYecFlg the value for CUS_ACCOUNT.IS_YEC_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setIsYecFlg(String isYecFlg) {
        this.isYecFlg = isYecFlg == null ? null : isYecFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.CARD_VALID_TILL_DT
     *
     * @return the value of CUS_ACCOUNT.CARD_VALID_TILL_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public Date getCardValidTillDt() {
        return cardValidTillDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.CARD_VALID_TILL_DT
     *
     * @param cardValidTillDt the value for CUS_ACCOUNT.CARD_VALID_TILL_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setCardValidTillDt(Date cardValidTillDt) {
        this.cardValidTillDt = cardValidTillDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.IGNORE_FLG
     *
     * @return the value of CUS_ACCOUNT.IGNORE_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getIgnoreFlg() {
        return ignoreFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.IGNORE_FLG
     *
     * @param ignoreFlg the value for CUS_ACCOUNT.IGNORE_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setIgnoreFlg(String ignoreFlg) {
        this.ignoreFlg = ignoreFlg == null ? null : ignoreFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.LAST_ACT_DT
     *
     * @return the value of CUS_ACCOUNT.LAST_ACT_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public Date getLastActDt() {
        return lastActDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.LAST_ACT_DT
     *
     * @param lastActDt the value for CUS_ACCOUNT.LAST_ACT_DT
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setLastActDt(Date lastActDt) {
        this.lastActDt = lastActDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.HV_FLG
     *
     * @return the value of CUS_ACCOUNT.HV_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getHvFlg() {
        return hvFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.HV_FLG
     *
     * @param hvFlg the value for CUS_ACCOUNT.HV_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setHvFlg(String hvFlg) {
        this.hvFlg = hvFlg == null ? null : hvFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.ACV_VALUE
     *
     * @return the value of CUS_ACCOUNT.ACV_VALUE
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getAcvValue() {
        return acvValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.ACV_VALUE
     *
     * @param acvValue the value for CUS_ACCOUNT.ACV_VALUE
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setAcvValue(String acvValue) {
        this.acvValue = acvValue == null ? null : acvValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.AIRLINE_TIER
     *
     * @return the value of CUS_ACCOUNT.AIRLINE_TIER
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getAirlineTier() {
        return airlineTier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.AIRLINE_TIER
     *
     * @param airlineTier the value for CUS_ACCOUNT.AIRLINE_TIER
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setAirlineTier(String airlineTier) {
        this.airlineTier = airlineTier == null ? null : airlineTier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_ACCOUNT.ACV_OVERRIDE_FLG
     *
     * @return the value of CUS_ACCOUNT.ACV_OVERRIDE_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public String getAcvOverrideFlg() {
        return acvOverrideFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_ACCOUNT.ACV_OVERRIDE_FLG
     *
     * @param acvOverrideFlg the value for CUS_ACCOUNT.ACV_OVERRIDE_FLG
     * @mbggenerated Tue Oct 16 11:22:19 IST 2018
     */
    public void setAcvOverrideFlg(String acvOverrideFlg) {
        this.acvOverrideFlg = acvOverrideFlg == null ? null : acvOverrideFlg.trim();
    }

  
}