package MARMSUI.migration.model;

import java.util.Date;

public class CusCreditCard {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.RCRE_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String rcreUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.RCRE_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private Date rcreDt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.LCHG_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String lchgUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.LCHG_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private Date lchgDt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.INT_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private Long intId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_TYPE_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardTypeCd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_BANK_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardBankCd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_BRAND_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardBrandCd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_NO
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_EXP_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private Date crCardExpDt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_COBRAND_FLG
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardCobrandFlg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardBankCtryCd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_BANK_TXT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardBankTxt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_TXT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String crCardBankCtryTxt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.TOKEN
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String token;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.PAYMENTCURRENCY
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String paymentcurrency;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.DEFAULTCARDFLAG
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String defaultcardflag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_CREDIT_CARD.CARDHOLDERNAME
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	private String cardholdername;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.RCRE_USER_ID
	 *
	 * @return the value of CUS_CREDIT_CARD.RCRE_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getRcreUserId() {
		return rcreUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.RCRE_USER_ID
	 *
	 * @param rcreUserId the value for CUS_CREDIT_CARD.RCRE_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setRcreUserId(String rcreUserId) {
		this.rcreUserId = rcreUserId == null ? null : rcreUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.RCRE_DT
	 *
	 * @return the value of CUS_CREDIT_CARD.RCRE_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public Date getRcreDt() {
		return rcreDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.RCRE_DT
	 *
	 * @param rcreDt the value for CUS_CREDIT_CARD.RCRE_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setRcreDt(Date rcreDt) {
		this.rcreDt = rcreDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.LCHG_USER_ID
	 *
	 * @return the value of CUS_CREDIT_CARD.LCHG_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getLchgUserId() {
		return lchgUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.LCHG_USER_ID
	 *
	 * @param lchgUserId the value for CUS_CREDIT_CARD.LCHG_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setLchgUserId(String lchgUserId) {
		this.lchgUserId = lchgUserId == null ? null : lchgUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.LCHG_DT
	 *
	 * @return the value of CUS_CREDIT_CARD.LCHG_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public Date getLchgDt() {
		return lchgDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.LCHG_DT
	 *
	 * @param lchgDt the value for CUS_CREDIT_CARD.LCHG_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setLchgDt(Date lchgDt) {
		this.lchgDt = lchgDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.INT_ID
	 *
	 * @return the value of CUS_CREDIT_CARD.INT_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public Long getIntId() {
		return intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.INT_ID
	 *
	 * @param intId the value for CUS_CREDIT_CARD.INT_ID
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setIntId(Long intId) {
		this.intId = intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_TYPE_CD
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_TYPE_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardTypeCd() {
		return crCardTypeCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_TYPE_CD
	 *
	 * @param crCardTypeCd the value for CUS_CREDIT_CARD.CR_CARD_TYPE_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardTypeCd(String crCardTypeCd) {
		this.crCardTypeCd = crCardTypeCd == null ? null : crCardTypeCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_BANK_CD
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_BANK_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardBankCd() {
		return crCardBankCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_BANK_CD
	 *
	 * @param crCardBankCd the value for CUS_CREDIT_CARD.CR_CARD_BANK_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardBankCd(String crCardBankCd) {
		this.crCardBankCd = crCardBankCd == null ? null : crCardBankCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_BRAND_CD
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_BRAND_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardBrandCd() {
		return crCardBrandCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_BRAND_CD
	 *
	 * @param crCardBrandCd the value for CUS_CREDIT_CARD.CR_CARD_BRAND_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardBrandCd(String crCardBrandCd) {
		this.crCardBrandCd = crCardBrandCd == null ? null : crCardBrandCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_NO
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_NO
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardNo() {
		return crCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_NO
	 *
	 * @param crCardNo the value for CUS_CREDIT_CARD.CR_CARD_NO
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardNo(String crCardNo) {
		this.crCardNo = crCardNo == null ? null : crCardNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_EXP_DT
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_EXP_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public Date getCrCardExpDt() {
		return crCardExpDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_EXP_DT
	 *
	 * @param crCardExpDt the value for CUS_CREDIT_CARD.CR_CARD_EXP_DT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardExpDt(Date crCardExpDt) {
		this.crCardExpDt = crCardExpDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_COBRAND_FLG
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_COBRAND_FLG
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardCobrandFlg() {
		return crCardCobrandFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_COBRAND_FLG
	 *
	 * @param crCardCobrandFlg the value for CUS_CREDIT_CARD.CR_CARD_COBRAND_FLG
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardCobrandFlg(String crCardCobrandFlg) {
		this.crCardCobrandFlg = crCardCobrandFlg == null ? null : crCardCobrandFlg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_CD
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardBankCtryCd() {
		return crCardBankCtryCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_CD
	 *
	 * @param crCardBankCtryCd the value for CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_CD
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardBankCtryCd(String crCardBankCtryCd) {
		this.crCardBankCtryCd = crCardBankCtryCd == null ? null : crCardBankCtryCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_BANK_TXT
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_BANK_TXT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardBankTxt() {
		return crCardBankTxt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_BANK_TXT
	 *
	 * @param crCardBankTxt the value for CUS_CREDIT_CARD.CR_CARD_BANK_TXT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardBankTxt(String crCardBankTxt) {
		this.crCardBankTxt = crCardBankTxt == null ? null : crCardBankTxt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_TXT
	 *
	 * @return the value of CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_TXT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCrCardBankCtryTxt() {
		return crCardBankCtryTxt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_TXT
	 *
	 * @param crCardBankCtryTxt the value for CUS_CREDIT_CARD.CR_CARD_BANK_CTRY_TXT
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCrCardBankCtryTxt(String crCardBankCtryTxt) {
		this.crCardBankCtryTxt = crCardBankCtryTxt == null ? null : crCardBankCtryTxt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.TOKEN
	 *
	 * @return the value of CUS_CREDIT_CARD.TOKEN
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.TOKEN
	 *
	 * @param token the value for CUS_CREDIT_CARD.TOKEN
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setToken(String token) {
		this.token = token == null ? null : token.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.PAYMENTCURRENCY
	 *
	 * @return the value of CUS_CREDIT_CARD.PAYMENTCURRENCY
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getPaymentcurrency() {
		return paymentcurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.PAYMENTCURRENCY
	 *
	 * @param paymentcurrency the value for CUS_CREDIT_CARD.PAYMENTCURRENCY
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setPaymentcurrency(String paymentcurrency) {
		this.paymentcurrency = paymentcurrency == null ? null : paymentcurrency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.DEFAULTCARDFLAG
	 *
	 * @return the value of CUS_CREDIT_CARD.DEFAULTCARDFLAG
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getDefaultcardflag() {
		return defaultcardflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.DEFAULTCARDFLAG
	 *
	 * @param defaultcardflag the value for CUS_CREDIT_CARD.DEFAULTCARDFLAG
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setDefaultcardflag(String defaultcardflag) {
		this.defaultcardflag = defaultcardflag == null ? null : defaultcardflag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_CREDIT_CARD.CARDHOLDERNAME
	 *
	 * @return the value of CUS_CREDIT_CARD.CARDHOLDERNAME
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public String getCardholdername() {
		return cardholdername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_CREDIT_CARD.CARDHOLDERNAME
	 *
	 * @param cardholdername the value for CUS_CREDIT_CARD.CARDHOLDERNAME
	 *
	 * @mbggenerated Mon Sep 24 10:37:21 IST 2018
	 */
	public void setCardholdername(String cardholdername) {
		this.cardholdername = cardholdername == null ? null : cardholdername.trim();
	}
}