package MARMSUI.migration.model;

public class CusGuardianInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Long intId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.SEQ_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Short seqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.INT_ID
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.INT_ID
     *
     * @param intId the value for MRM.CUS_GUARDIAN_INFO.INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.SEQ_NO
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.SEQ_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Short getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.SEQ_NO
     *
     * @param seqNo the value for MRM.CUS_GUARDIAN_INFO.SEQ_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setSeqNo(Short seqNo) {
        this.seqNo = seqNo;
    }
}