package MARMSUI.migration.model;

import java.util.Date;

public class CusGuardianInfo extends CusGuardianInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.RCRE_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String rcreUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.RCRE_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Date rcreDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.LCHG_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String lchgUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.LCHG_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Date lchgDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.FAMILY_NAME
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.GIVEN_NAME
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String givenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.TITLE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.GENDER
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String relnToMbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR_TXT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String relnToMbrTxt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_1
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeAddrLine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_2
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeAddrLine2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_3
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeAddrLine3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_4
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeAddrLine4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_CTY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeCtyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_STATE_PROV
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeStateProv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeCtryCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_ZIP_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeZipCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_RGN_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homeRgnCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homePhoneCtryCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE_AREA_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homePhoneAreaCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String homePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_1
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyAddrLine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_2
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyAddrLine2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_3
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyAddrLine3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_4
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyAddrLine4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_CTY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyCtyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_STATE_PROV
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyStateProv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyCtryCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_ZIP_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyZipCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_RGN_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyRgnCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyPhoneCtryCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE_AREA_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyPhoneAreaCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String coyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String guardianIntId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_PRG_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String guardianPrgCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_CONSENT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String guardianConsent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_LINK
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String guardianLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_GUARDIAN_INFO.LINK_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Date linkDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.RCRE_USER_ID
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.RCRE_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.RCRE_USER_ID
     *
     * @param rcreUserId the value for MRM.CUS_GUARDIAN_INFO.RCRE_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.RCRE_DT
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.RCRE_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.RCRE_DT
     *
     * @param rcreDt the value for MRM.CUS_GUARDIAN_INFO.RCRE_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.LCHG_USER_ID
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.LCHG_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.LCHG_USER_ID
     *
     * @param lchgUserId the value for MRM.CUS_GUARDIAN_INFO.LCHG_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.LCHG_DT
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.LCHG_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.LCHG_DT
     *
     * @param lchgDt the value for MRM.CUS_GUARDIAN_INFO.LCHG_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.FAMILY_NAME
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.FAMILY_NAME
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.FAMILY_NAME
     *
     * @param familyName the value for MRM.CUS_GUARDIAN_INFO.FAMILY_NAME
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.GIVEN_NAME
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.GIVEN_NAME
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.GIVEN_NAME
     *
     * @param givenName the value for MRM.CUS_GUARDIAN_INFO.GIVEN_NAME
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.TITLE
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.TITLE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.TITLE
     *
     * @param title the value for MRM.CUS_GUARDIAN_INFO.TITLE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.GENDER
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.GENDER
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.GENDER
     *
     * @param gender the value for MRM.CUS_GUARDIAN_INFO.GENDER
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getRelnToMbr() {
        return relnToMbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR
     *
     * @param relnToMbr the value for MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setRelnToMbr(String relnToMbr) {
        this.relnToMbr = relnToMbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR_TXT
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR_TXT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getRelnToMbrTxt() {
        return relnToMbrTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR_TXT
     *
     * @param relnToMbrTxt the value for MRM.CUS_GUARDIAN_INFO.RELN_TO_MBR_TXT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setRelnToMbrTxt(String relnToMbrTxt) {
        this.relnToMbrTxt = relnToMbrTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_1
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_1
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeAddrLine1() {
        return homeAddrLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_1
     *
     * @param homeAddrLine1 the value for MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_1
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeAddrLine1(String homeAddrLine1) {
        this.homeAddrLine1 = homeAddrLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_2
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_2
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeAddrLine2() {
        return homeAddrLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_2
     *
     * @param homeAddrLine2 the value for MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_2
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeAddrLine2(String homeAddrLine2) {
        this.homeAddrLine2 = homeAddrLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_3
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_3
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeAddrLine3() {
        return homeAddrLine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_3
     *
     * @param homeAddrLine3 the value for MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_3
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeAddrLine3(String homeAddrLine3) {
        this.homeAddrLine3 = homeAddrLine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_4
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_4
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeAddrLine4() {
        return homeAddrLine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_4
     *
     * @param homeAddrLine4 the value for MRM.CUS_GUARDIAN_INFO.HOME_ADDR_LINE_4
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeAddrLine4(String homeAddrLine4) {
        this.homeAddrLine4 = homeAddrLine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_CTY_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_CTY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeCtyCd() {
        return homeCtyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_CTY_CD
     *
     * @param homeCtyCd the value for MRM.CUS_GUARDIAN_INFO.HOME_CTY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeCtyCd(String homeCtyCd) {
        this.homeCtyCd = homeCtyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_STATE_PROV
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_STATE_PROV
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeStateProv() {
        return homeStateProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_STATE_PROV
     *
     * @param homeStateProv the value for MRM.CUS_GUARDIAN_INFO.HOME_STATE_PROV
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeStateProv(String homeStateProv) {
        this.homeStateProv = homeStateProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_CTRY_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeCtryCd() {
        return homeCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_CTRY_CD
     *
     * @param homeCtryCd the value for MRM.CUS_GUARDIAN_INFO.HOME_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeCtryCd(String homeCtryCd) {
        this.homeCtryCd = homeCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ZIP_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_ZIP_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeZipCd() {
        return homeZipCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_ZIP_CD
     *
     * @param homeZipCd the value for MRM.CUS_GUARDIAN_INFO.HOME_ZIP_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeZipCd(String homeZipCd) {
        this.homeZipCd = homeZipCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_RGN_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_RGN_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomeRgnCd() {
        return homeRgnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_RGN_CD
     *
     * @param homeRgnCd the value for MRM.CUS_GUARDIAN_INFO.HOME_RGN_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomeRgnCd(String homeRgnCd) {
        this.homeRgnCd = homeRgnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE_CTRY_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_PHONE_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomePhoneCtryCd() {
        return homePhoneCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE_CTRY_CD
     *
     * @param homePhoneCtryCd the value for MRM.CUS_GUARDIAN_INFO.HOME_PHONE_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomePhoneCtryCd(String homePhoneCtryCd) {
        this.homePhoneCtryCd = homePhoneCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE_AREA_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_PHONE_AREA_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomePhoneAreaCd() {
        return homePhoneAreaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE_AREA_CD
     *
     * @param homePhoneAreaCd the value for MRM.CUS_GUARDIAN_INFO.HOME_PHONE_AREA_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomePhoneAreaCd(String homePhoneAreaCd) {
        this.homePhoneAreaCd = homePhoneAreaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.HOME_PHONE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.HOME_PHONE
     *
     * @param homePhone the value for MRM.CUS_GUARDIAN_INFO.HOME_PHONE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_1
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_1
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyAddrLine1() {
        return coyAddrLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_1
     *
     * @param coyAddrLine1 the value for MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_1
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyAddrLine1(String coyAddrLine1) {
        this.coyAddrLine1 = coyAddrLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_2
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_2
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyAddrLine2() {
        return coyAddrLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_2
     *
     * @param coyAddrLine2 the value for MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_2
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyAddrLine2(String coyAddrLine2) {
        this.coyAddrLine2 = coyAddrLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_3
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_3
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyAddrLine3() {
        return coyAddrLine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_3
     *
     * @param coyAddrLine3 the value for MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_3
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyAddrLine3(String coyAddrLine3) {
        this.coyAddrLine3 = coyAddrLine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_4
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_4
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyAddrLine4() {
        return coyAddrLine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_4
     *
     * @param coyAddrLine4 the value for MRM.CUS_GUARDIAN_INFO.COY_ADDR_LINE_4
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyAddrLine4(String coyAddrLine4) {
        this.coyAddrLine4 = coyAddrLine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_CTY_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_CTY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyCtyCd() {
        return coyCtyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_CTY_CD
     *
     * @param coyCtyCd the value for MRM.CUS_GUARDIAN_INFO.COY_CTY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyCtyCd(String coyCtyCd) {
        this.coyCtyCd = coyCtyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_STATE_PROV
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_STATE_PROV
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyStateProv() {
        return coyStateProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_STATE_PROV
     *
     * @param coyStateProv the value for MRM.CUS_GUARDIAN_INFO.COY_STATE_PROV
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyStateProv(String coyStateProv) {
        this.coyStateProv = coyStateProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_CTRY_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyCtryCd() {
        return coyCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_CTRY_CD
     *
     * @param coyCtryCd the value for MRM.CUS_GUARDIAN_INFO.COY_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyCtryCd(String coyCtryCd) {
        this.coyCtryCd = coyCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ZIP_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_ZIP_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyZipCd() {
        return coyZipCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_ZIP_CD
     *
     * @param coyZipCd the value for MRM.CUS_GUARDIAN_INFO.COY_ZIP_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyZipCd(String coyZipCd) {
        this.coyZipCd = coyZipCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_RGN_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_RGN_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyRgnCd() {
        return coyRgnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_RGN_CD
     *
     * @param coyRgnCd the value for MRM.CUS_GUARDIAN_INFO.COY_RGN_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyRgnCd(String coyRgnCd) {
        this.coyRgnCd = coyRgnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE_CTRY_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_PHONE_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyPhoneCtryCd() {
        return coyPhoneCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE_CTRY_CD
     *
     * @param coyPhoneCtryCd the value for MRM.CUS_GUARDIAN_INFO.COY_PHONE_CTRY_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyPhoneCtryCd(String coyPhoneCtryCd) {
        this.coyPhoneCtryCd = coyPhoneCtryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE_AREA_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_PHONE_AREA_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyPhoneAreaCd() {
        return coyPhoneAreaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE_AREA_CD
     *
     * @param coyPhoneAreaCd the value for MRM.CUS_GUARDIAN_INFO.COY_PHONE_AREA_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyPhoneAreaCd(String coyPhoneAreaCd) {
        this.coyPhoneAreaCd = coyPhoneAreaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.COY_PHONE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getCoyPhone() {
        return coyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.COY_PHONE
     *
     * @param coyPhone the value for MRM.CUS_GUARDIAN_INFO.COY_PHONE
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setCoyPhone(String coyPhone) {
        this.coyPhone = coyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_INT_ID
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.GUARDIAN_INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getGuardianIntId() {
        return guardianIntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_INT_ID
     *
     * @param guardianIntId the value for MRM.CUS_GUARDIAN_INFO.GUARDIAN_INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setGuardianIntId(String guardianIntId) {
        this.guardianIntId = guardianIntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_PRG_CD
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.GUARDIAN_PRG_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getGuardianPrgCd() {
        return guardianPrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_PRG_CD
     *
     * @param guardianPrgCd the value for MRM.CUS_GUARDIAN_INFO.GUARDIAN_PRG_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setGuardianPrgCd(String guardianPrgCd) {
        this.guardianPrgCd = guardianPrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_CONSENT
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.GUARDIAN_CONSENT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getGuardianConsent() {
        return guardianConsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_CONSENT
     *
     * @param guardianConsent the value for MRM.CUS_GUARDIAN_INFO.GUARDIAN_CONSENT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setGuardianConsent(String guardianConsent) {
        this.guardianConsent = guardianConsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_LINK
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.GUARDIAN_LINK
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getGuardianLink() {
        return guardianLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.GUARDIAN_LINK
     *
     * @param guardianLink the value for MRM.CUS_GUARDIAN_INFO.GUARDIAN_LINK
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setGuardianLink(String guardianLink) {
        this.guardianLink = guardianLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_GUARDIAN_INFO.LINK_DT
     *
     * @return the value of MRM.CUS_GUARDIAN_INFO.LINK_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Date getLinkDt() {
        return linkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_GUARDIAN_INFO.LINK_DT
     *
     * @param linkDt the value for MRM.CUS_GUARDIAN_INFO.LINK_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setLinkDt(Date linkDt) {
        this.linkDt = linkDt;
    }
}