package MARMSUI.migration.model;

import java.util.Date;

public class CusOffpInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.RCRE_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String rcreUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.RCRE_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Date rcreDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.LCHG_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String lchgUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.LCHG_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Date lchgDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Long intId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.SEQ_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private Short seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.FFP_PRT_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String ffpPrtCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.FFP_MBR_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String ffpMbrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.LINK_STATUS
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String linkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.STATUS_MATCH
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String statusMatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRM.CUS_OFFP_INFO.PARTNER_TIER
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    private String partnerTier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.RCRE_USER_ID
     *
     * @return the value of MRM.CUS_OFFP_INFO.RCRE_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.RCRE_USER_ID
     *
     * @param rcreUserId the value for MRM.CUS_OFFP_INFO.RCRE_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.RCRE_DT
     *
     * @return the value of MRM.CUS_OFFP_INFO.RCRE_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.RCRE_DT
     *
     * @param rcreDt the value for MRM.CUS_OFFP_INFO.RCRE_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.LCHG_USER_ID
     *
     * @return the value of MRM.CUS_OFFP_INFO.LCHG_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.LCHG_USER_ID
     *
     * @param lchgUserId the value for MRM.CUS_OFFP_INFO.LCHG_USER_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.LCHG_DT
     *
     * @return the value of MRM.CUS_OFFP_INFO.LCHG_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.LCHG_DT
     *
     * @param lchgDt the value for MRM.CUS_OFFP_INFO.LCHG_DT
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.INT_ID
     *
     * @return the value of MRM.CUS_OFFP_INFO.INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.INT_ID
     *
     * @param intId the value for MRM.CUS_OFFP_INFO.INT_ID
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.SEQ_NO
     *
     * @return the value of MRM.CUS_OFFP_INFO.SEQ_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public Short getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.SEQ_NO
     *
     * @param seqNo the value for MRM.CUS_OFFP_INFO.SEQ_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setSeqNo(Short seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.FFP_PRT_CD
     *
     * @return the value of MRM.CUS_OFFP_INFO.FFP_PRT_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getFfpPrtCd() {
        return ffpPrtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.FFP_PRT_CD
     *
     * @param ffpPrtCd the value for MRM.CUS_OFFP_INFO.FFP_PRT_CD
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setFfpPrtCd(String ffpPrtCd) {
        this.ffpPrtCd = ffpPrtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.FFP_MBR_NO
     *
     * @return the value of MRM.CUS_OFFP_INFO.FFP_MBR_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getFfpMbrNo() {
        return ffpMbrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.FFP_MBR_NO
     *
     * @param ffpMbrNo the value for MRM.CUS_OFFP_INFO.FFP_MBR_NO
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setFfpMbrNo(String ffpMbrNo) {
        this.ffpMbrNo = ffpMbrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.LINK_STATUS
     *
     * @return the value of MRM.CUS_OFFP_INFO.LINK_STATUS
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getLinkStatus() {
        return linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.LINK_STATUS
     *
     * @param linkStatus the value for MRM.CUS_OFFP_INFO.LINK_STATUS
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setLinkStatus(String linkStatus) {
        this.linkStatus = linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.STATUS_MATCH
     *
     * @return the value of MRM.CUS_OFFP_INFO.STATUS_MATCH
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getStatusMatch() {
        return statusMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.STATUS_MATCH
     *
     * @param statusMatch the value for MRM.CUS_OFFP_INFO.STATUS_MATCH
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setStatusMatch(String statusMatch) {
        this.statusMatch = statusMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRM.CUS_OFFP_INFO.PARTNER_TIER
     *
     * @return the value of MRM.CUS_OFFP_INFO.PARTNER_TIER
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public String getPartnerTier() {
        return partnerTier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRM.CUS_OFFP_INFO.PARTNER_TIER
     *
     * @param partnerTier the value for MRM.CUS_OFFP_INFO.PARTNER_TIER
     *
     * @mbg.generated Tue Jul 25 17:37:14 SGT 2023
     */
    public void setPartnerTier(String partnerTier) {
        this.partnerTier = partnerTier;
    }
}