/* 
* =============================================================================== 
* For internal use of Singapore Airlines and TATA Consultancy Services only. 
* (C) 2019 Singapore Airlines. 
* Singapore Co. Reg. No. 197200078R. All Rights Reserved. 
* 
* Information in this file is the intellectual property of SINGAPORE AIRLINES. 
* =============================================================================== 
*/

package MARMSUI.migration.model;


import java.util.Date;

public class CusPers implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Long intId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.RCRE_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String rcreUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.RCRE_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Date rcreDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.LCHG_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String lchgUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.LCHG_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Date lchgDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.FAMILY_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String familyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.GIVEN_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String givenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.TITLE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.CARD_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.GENDER
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.DOB
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Date dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.NATIONALITY_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String nationalityCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.CTRY_OF_BIRTH
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String ctryOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.MARITAL_STATUS_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String maritalStatusInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PASSPORT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String passportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PASSPORT_EXP_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Date passportExpDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.STAFF_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.FORM_OF_ENR_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String formOfEnrInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.SRC_OF_ENR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String srcOfEnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.ENR_CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String enrCreateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.ENR_CREATE_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Date enrCreateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.ENR_CREATE_CTY_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String enrCreateCtyCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.ENR_CREATE_SUBSRC
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String enrCreateSubsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.DT_OF_ENR_FORM_RECEIPT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Date dtOfEnrFormReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.SRC_OF_PRG_INFO_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String srcOfPrgInfoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.SRC_OF_PRG_INFO_TXT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String srcOfPrgInfoTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.INTRODUCER_INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String introducerIntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PARTNER_PROMO_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String partnerPromoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PREF_LANG_WRITTEN_1
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String prefLangWritten1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PREF_LANG_WRITTEN_2
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String prefLangWritten2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PREF_LANG_SPOKEN_1
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String prefLangSpoken1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PREF_LANG_SPOKEN_2
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String prefLangSpoken2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PREF_LANG_LOCAL_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String prefLangLocalFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.STOP_MAIL_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String stopMailInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.EMAIL_ADDR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String emailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.ALT_EMAIL_ADDR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String altEmailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.CORRES_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String corresName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.MAILING_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String mailingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.MAIL_ADDR_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String mailAddrInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.VIP_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String vipFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.BLK_CUS_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String blkCusFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.DEDUP_STATUS
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String dedupStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PRINCIPAL_INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String principalIntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.COBRAND_ACTIVATE_PRT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String cobrandActivatePrt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.FRM_PEND_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String frmPendFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.SPL_CUS_TYPE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String splCusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.INTRODUCER_PRG_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String introducerPrgCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.DIRECT_MAIL_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String directMailInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.PASSPORT_ISS_CTRY
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String passportIssCtry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.CTRY_OF_RESIDENCE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String ctryOfResidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.LAST_VERIFIED
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private Date lastVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.EU_RESIDNT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String euResidnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.IP_ADDRESS
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.UUID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    private String uuid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.EMAIL_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    private String emailVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.MOBILE_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    private String mobileVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.LAST_EMAIL_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    private Date lastEmailVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PERS.LAST_MOBILE_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    private Date lastMobileVerified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.INT_ID
     *
     * @return the value of CUS_PERS.INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.INT_ID
     *
     * @param intId the value for CUS_PERS.INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.RCRE_USER_ID
     *
     * @return the value of CUS_PERS.RCRE_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.RCRE_USER_ID
     *
     * @param rcreUserId the value for CUS_PERS.RCRE_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId == null ? null : rcreUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.RCRE_DT
     *
     * @return the value of CUS_PERS.RCRE_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.RCRE_DT
     *
     * @param rcreDt the value for CUS_PERS.RCRE_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.LCHG_USER_ID
     *
     * @return the value of CUS_PERS.LCHG_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.LCHG_USER_ID
     *
     * @param lchgUserId the value for CUS_PERS.LCHG_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId == null ? null : lchgUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.LCHG_DT
     *
     * @return the value of CUS_PERS.LCHG_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.LCHG_DT
     *
     * @param lchgDt the value for CUS_PERS.LCHG_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.FAMILY_NAME
     *
     * @return the value of CUS_PERS.FAMILY_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.FAMILY_NAME
     *
     * @param familyName the value for CUS_PERS.FAMILY_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.GIVEN_NAME
     *
     * @return the value of CUS_PERS.GIVEN_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.GIVEN_NAME
     *
     * @param givenName the value for CUS_PERS.GIVEN_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setGivenName(String givenName) {
        this.givenName = givenName == null ? null : givenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.TITLE
     *
     * @return the value of CUS_PERS.TITLE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.TITLE
     *
     * @param title the value for CUS_PERS.TITLE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.CARD_NAME
     *
     * @return the value of CUS_PERS.CARD_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.CARD_NAME
     *
     * @param cardName the value for CUS_PERS.CARD_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.GENDER
     *
     * @return the value of CUS_PERS.GENDER
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.GENDER
     *
     * @param gender the value for CUS_PERS.GENDER
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.DOB
     *
     * @return the value of CUS_PERS.DOB
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.DOB
     *
     * @param dob the value for CUS_PERS.DOB
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.NATIONALITY_CD
     *
     * @return the value of CUS_PERS.NATIONALITY_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getNationalityCd() {
        return nationalityCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.NATIONALITY_CD
     *
     * @param nationalityCd the value for CUS_PERS.NATIONALITY_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setNationalityCd(String nationalityCd) {
        this.nationalityCd = nationalityCd == null ? null : nationalityCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.CTRY_OF_BIRTH
     *
     * @return the value of CUS_PERS.CTRY_OF_BIRTH
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getCtryOfBirth() {
        return ctryOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.CTRY_OF_BIRTH
     *
     * @param ctryOfBirth the value for CUS_PERS.CTRY_OF_BIRTH
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setCtryOfBirth(String ctryOfBirth) {
        this.ctryOfBirth = ctryOfBirth == null ? null : ctryOfBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.MARITAL_STATUS_IND
     *
     * @return the value of CUS_PERS.MARITAL_STATUS_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getMaritalStatusInd() {
        return maritalStatusInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.MARITAL_STATUS_IND
     *
     * @param maritalStatusInd the value for CUS_PERS.MARITAL_STATUS_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setMaritalStatusInd(String maritalStatusInd) {
        this.maritalStatusInd = maritalStatusInd == null ? null : maritalStatusInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PASSPORT_ID
     *
     * @return the value of CUS_PERS.PASSPORT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPassportId() {
        return passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PASSPORT_ID
     *
     * @param passportId the value for CUS_PERS.PASSPORT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPassportId(String passportId) {
        this.passportId = passportId == null ? null : passportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PASSPORT_EXP_DT
     *
     * @return the value of CUS_PERS.PASSPORT_EXP_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Date getPassportExpDt() {
        return passportExpDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PASSPORT_EXP_DT
     *
     * @param passportExpDt the value for CUS_PERS.PASSPORT_EXP_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPassportExpDt(Date passportExpDt) {
        this.passportExpDt = passportExpDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.STAFF_ID
     *
     * @return the value of CUS_PERS.STAFF_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.STAFF_ID
     *
     * @param staffId the value for CUS_PERS.STAFF_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.FORM_OF_ENR_IND
     *
     * @return the value of CUS_PERS.FORM_OF_ENR_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getFormOfEnrInd() {
        return formOfEnrInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.FORM_OF_ENR_IND
     *
     * @param formOfEnrInd the value for CUS_PERS.FORM_OF_ENR_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setFormOfEnrInd(String formOfEnrInd) {
        this.formOfEnrInd = formOfEnrInd == null ? null : formOfEnrInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.SRC_OF_ENR
     *
     * @return the value of CUS_PERS.SRC_OF_ENR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getSrcOfEnr() {
        return srcOfEnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.SRC_OF_ENR
     *
     * @param srcOfEnr the value for CUS_PERS.SRC_OF_ENR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setSrcOfEnr(String srcOfEnr) {
        this.srcOfEnr = srcOfEnr == null ? null : srcOfEnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.ENR_CREATE_USER_ID
     *
     * @return the value of CUS_PERS.ENR_CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getEnrCreateUserId() {
        return enrCreateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.ENR_CREATE_USER_ID
     *
     * @param enrCreateUserId the value for CUS_PERS.ENR_CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setEnrCreateUserId(String enrCreateUserId) {
        this.enrCreateUserId = enrCreateUserId == null ? null : enrCreateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.ENR_CREATE_DT
     *
     * @return the value of CUS_PERS.ENR_CREATE_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Date getEnrCreateDt() {
        return enrCreateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.ENR_CREATE_DT
     *
     * @param enrCreateDt the value for CUS_PERS.ENR_CREATE_DT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setEnrCreateDt(Date enrCreateDt) {
        this.enrCreateDt = enrCreateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.ENR_CREATE_CTY_CD
     *
     * @return the value of CUS_PERS.ENR_CREATE_CTY_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getEnrCreateCtyCd() {
        return enrCreateCtyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.ENR_CREATE_CTY_CD
     *
     * @param enrCreateCtyCd the value for CUS_PERS.ENR_CREATE_CTY_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setEnrCreateCtyCd(String enrCreateCtyCd) {
        this.enrCreateCtyCd = enrCreateCtyCd == null ? null : enrCreateCtyCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.ENR_CREATE_SUBSRC
     *
     * @return the value of CUS_PERS.ENR_CREATE_SUBSRC
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getEnrCreateSubsrc() {
        return enrCreateSubsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.ENR_CREATE_SUBSRC
     *
     * @param enrCreateSubsrc the value for CUS_PERS.ENR_CREATE_SUBSRC
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setEnrCreateSubsrc(String enrCreateSubsrc) {
        this.enrCreateSubsrc = enrCreateSubsrc == null ? null : enrCreateSubsrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.DT_OF_ENR_FORM_RECEIPT
     *
     * @return the value of CUS_PERS.DT_OF_ENR_FORM_RECEIPT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Date getDtOfEnrFormReceipt() {
        return dtOfEnrFormReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.DT_OF_ENR_FORM_RECEIPT
     *
     * @param dtOfEnrFormReceipt the value for CUS_PERS.DT_OF_ENR_FORM_RECEIPT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setDtOfEnrFormReceipt(Date dtOfEnrFormReceipt) {
        this.dtOfEnrFormReceipt = dtOfEnrFormReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.SRC_OF_PRG_INFO_CD
     *
     * @return the value of CUS_PERS.SRC_OF_PRG_INFO_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getSrcOfPrgInfoCd() {
        return srcOfPrgInfoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.SRC_OF_PRG_INFO_CD
     *
     * @param srcOfPrgInfoCd the value for CUS_PERS.SRC_OF_PRG_INFO_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setSrcOfPrgInfoCd(String srcOfPrgInfoCd) {
        this.srcOfPrgInfoCd = srcOfPrgInfoCd == null ? null : srcOfPrgInfoCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.SRC_OF_PRG_INFO_TXT
     *
     * @return the value of CUS_PERS.SRC_OF_PRG_INFO_TXT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getSrcOfPrgInfoTxt() {
        return srcOfPrgInfoTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.SRC_OF_PRG_INFO_TXT
     *
     * @param srcOfPrgInfoTxt the value for CUS_PERS.SRC_OF_PRG_INFO_TXT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setSrcOfPrgInfoTxt(String srcOfPrgInfoTxt) {
        this.srcOfPrgInfoTxt = srcOfPrgInfoTxt == null ? null : srcOfPrgInfoTxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.INTRODUCER_INT_ID
     *
     * @return the value of CUS_PERS.INTRODUCER_INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getIntroducerIntId() {
        return introducerIntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.INTRODUCER_INT_ID
     *
     * @param introducerIntId the value for CUS_PERS.INTRODUCER_INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setIntroducerIntId(String introducerIntId) {
        this.introducerIntId = introducerIntId == null ? null : introducerIntId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PARTNER_PROMO_CD
     *
     * @return the value of CUS_PERS.PARTNER_PROMO_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPartnerPromoCd() {
        return partnerPromoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PARTNER_PROMO_CD
     *
     * @param partnerPromoCd the value for CUS_PERS.PARTNER_PROMO_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPartnerPromoCd(String partnerPromoCd) {
        this.partnerPromoCd = partnerPromoCd == null ? null : partnerPromoCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PREF_LANG_WRITTEN_1
     *
     * @return the value of CUS_PERS.PREF_LANG_WRITTEN_1
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPrefLangWritten1() {
        return prefLangWritten1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PREF_LANG_WRITTEN_1
     *
     * @param prefLangWritten1 the value for CUS_PERS.PREF_LANG_WRITTEN_1
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPrefLangWritten1(String prefLangWritten1) {
        this.prefLangWritten1 = prefLangWritten1 == null ? null : prefLangWritten1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PREF_LANG_WRITTEN_2
     *
     * @return the value of CUS_PERS.PREF_LANG_WRITTEN_2
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPrefLangWritten2() {
        return prefLangWritten2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PREF_LANG_WRITTEN_2
     *
     * @param prefLangWritten2 the value for CUS_PERS.PREF_LANG_WRITTEN_2
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPrefLangWritten2(String prefLangWritten2) {
        this.prefLangWritten2 = prefLangWritten2 == null ? null : prefLangWritten2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PREF_LANG_SPOKEN_1
     *
     * @return the value of CUS_PERS.PREF_LANG_SPOKEN_1
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPrefLangSpoken1() {
        return prefLangSpoken1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PREF_LANG_SPOKEN_1
     *
     * @param prefLangSpoken1 the value for CUS_PERS.PREF_LANG_SPOKEN_1
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPrefLangSpoken1(String prefLangSpoken1) {
        this.prefLangSpoken1 = prefLangSpoken1 == null ? null : prefLangSpoken1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PREF_LANG_SPOKEN_2
     *
     * @return the value of CUS_PERS.PREF_LANG_SPOKEN_2
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPrefLangSpoken2() {
        return prefLangSpoken2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PREF_LANG_SPOKEN_2
     *
     * @param prefLangSpoken2 the value for CUS_PERS.PREF_LANG_SPOKEN_2
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPrefLangSpoken2(String prefLangSpoken2) {
        this.prefLangSpoken2 = prefLangSpoken2 == null ? null : prefLangSpoken2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PREF_LANG_LOCAL_FLG
     *
     * @return the value of CUS_PERS.PREF_LANG_LOCAL_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPrefLangLocalFlg() {
        return prefLangLocalFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PREF_LANG_LOCAL_FLG
     *
     * @param prefLangLocalFlg the value for CUS_PERS.PREF_LANG_LOCAL_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPrefLangLocalFlg(String prefLangLocalFlg) {
        this.prefLangLocalFlg = prefLangLocalFlg == null ? null : prefLangLocalFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.STOP_MAIL_IND
     *
     * @return the value of CUS_PERS.STOP_MAIL_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getStopMailInd() {
        return stopMailInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.STOP_MAIL_IND
     *
     * @param stopMailInd the value for CUS_PERS.STOP_MAIL_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setStopMailInd(String stopMailInd) {
        this.stopMailInd = stopMailInd == null ? null : stopMailInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.EMAIL_ADDR
     *
     * @return the value of CUS_PERS.EMAIL_ADDR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.EMAIL_ADDR
     *
     * @param emailAddr the value for CUS_PERS.EMAIL_ADDR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr == null ? null : emailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.ALT_EMAIL_ADDR
     *
     * @return the value of CUS_PERS.ALT_EMAIL_ADDR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getAltEmailAddr() {
        return altEmailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.ALT_EMAIL_ADDR
     *
     * @param altEmailAddr the value for CUS_PERS.ALT_EMAIL_ADDR
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setAltEmailAddr(String altEmailAddr) {
        this.altEmailAddr = altEmailAddr == null ? null : altEmailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.CORRES_NAME
     *
     * @return the value of CUS_PERS.CORRES_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getCorresName() {
        return corresName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.CORRES_NAME
     *
     * @param corresName the value for CUS_PERS.CORRES_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setCorresName(String corresName) {
        this.corresName = corresName == null ? null : corresName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.MAILING_NAME
     *
     * @return the value of CUS_PERS.MAILING_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getMailingName() {
        return mailingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.MAILING_NAME
     *
     * @param mailingName the value for CUS_PERS.MAILING_NAME
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setMailingName(String mailingName) {
        this.mailingName = mailingName == null ? null : mailingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.MAIL_ADDR_IND
     *
     * @return the value of CUS_PERS.MAIL_ADDR_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getMailAddrInd() {
        return mailAddrInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.MAIL_ADDR_IND
     *
     * @param mailAddrInd the value for CUS_PERS.MAIL_ADDR_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setMailAddrInd(String mailAddrInd) {
        this.mailAddrInd = mailAddrInd == null ? null : mailAddrInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.VIP_FLG
     *
     * @return the value of CUS_PERS.VIP_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getVipFlg() {
        return vipFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.VIP_FLG
     *
     * @param vipFlg the value for CUS_PERS.VIP_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setVipFlg(String vipFlg) {
        this.vipFlg = vipFlg == null ? null : vipFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.BLK_CUS_FLG
     *
     * @return the value of CUS_PERS.BLK_CUS_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getBlkCusFlg() {
        return blkCusFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.BLK_CUS_FLG
     *
     * @param blkCusFlg the value for CUS_PERS.BLK_CUS_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setBlkCusFlg(String blkCusFlg) {
        this.blkCusFlg = blkCusFlg == null ? null : blkCusFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.DEDUP_STATUS
     *
     * @return the value of CUS_PERS.DEDUP_STATUS
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getDedupStatus() {
        return dedupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.DEDUP_STATUS
     *
     * @param dedupStatus the value for CUS_PERS.DEDUP_STATUS
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setDedupStatus(String dedupStatus) {
        this.dedupStatus = dedupStatus == null ? null : dedupStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PRINCIPAL_INT_ID
     *
     * @return the value of CUS_PERS.PRINCIPAL_INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPrincipalIntId() {
        return principalIntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PRINCIPAL_INT_ID
     *
     * @param principalIntId the value for CUS_PERS.PRINCIPAL_INT_ID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPrincipalIntId(String principalIntId) {
        this.principalIntId = principalIntId == null ? null : principalIntId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.COBRAND_ACTIVATE_PRT
     *
     * @return the value of CUS_PERS.COBRAND_ACTIVATE_PRT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getCobrandActivatePrt() {
        return cobrandActivatePrt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.COBRAND_ACTIVATE_PRT
     *
     * @param cobrandActivatePrt the value for CUS_PERS.COBRAND_ACTIVATE_PRT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setCobrandActivatePrt(String cobrandActivatePrt) {
        this.cobrandActivatePrt = cobrandActivatePrt == null ? null : cobrandActivatePrt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.FRM_PEND_FLG
     *
     * @return the value of CUS_PERS.FRM_PEND_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getFrmPendFlg() {
        return frmPendFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.FRM_PEND_FLG
     *
     * @param frmPendFlg the value for CUS_PERS.FRM_PEND_FLG
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setFrmPendFlg(String frmPendFlg) {
        this.frmPendFlg = frmPendFlg == null ? null : frmPendFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.SPL_CUS_TYPE
     *
     * @return the value of CUS_PERS.SPL_CUS_TYPE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getSplCusType() {
        return splCusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.SPL_CUS_TYPE
     *
     * @param splCusType the value for CUS_PERS.SPL_CUS_TYPE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setSplCusType(String splCusType) {
        this.splCusType = splCusType == null ? null : splCusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.INTRODUCER_PRG_CD
     *
     * @return the value of CUS_PERS.INTRODUCER_PRG_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getIntroducerPrgCd() {
        return introducerPrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.INTRODUCER_PRG_CD
     *
     * @param introducerPrgCd the value for CUS_PERS.INTRODUCER_PRG_CD
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setIntroducerPrgCd(String introducerPrgCd) {
        this.introducerPrgCd = introducerPrgCd == null ? null : introducerPrgCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.DIRECT_MAIL_IND
     *
     * @return the value of CUS_PERS.DIRECT_MAIL_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getDirectMailInd() {
        return directMailInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.DIRECT_MAIL_IND
     *
     * @param directMailInd the value for CUS_PERS.DIRECT_MAIL_IND
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setDirectMailInd(String directMailInd) {
        this.directMailInd = directMailInd == null ? null : directMailInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.PASSPORT_ISS_CTRY
     *
     * @return the value of CUS_PERS.PASSPORT_ISS_CTRY
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getPassportIssCtry() {
        return passportIssCtry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.PASSPORT_ISS_CTRY
     *
     * @param passportIssCtry the value for CUS_PERS.PASSPORT_ISS_CTRY
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setPassportIssCtry(String passportIssCtry) {
        this.passportIssCtry = passportIssCtry == null ? null : passportIssCtry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.CTRY_OF_RESIDENCE
     *
     * @return the value of CUS_PERS.CTRY_OF_RESIDENCE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getCtryOfResidence() {
        return ctryOfResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.CTRY_OF_RESIDENCE
     *
     * @param ctryOfResidence the value for CUS_PERS.CTRY_OF_RESIDENCE
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setCtryOfResidence(String ctryOfResidence) {
        this.ctryOfResidence = ctryOfResidence == null ? null : ctryOfResidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.LAST_VERIFIED
     *
     * @return the value of CUS_PERS.LAST_VERIFIED
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public Date getLastVerified() {
        return lastVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.LAST_VERIFIED
     *
     * @param lastVerified the value for CUS_PERS.LAST_VERIFIED
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setLastVerified(Date lastVerified) {
        this.lastVerified = lastVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.EU_RESIDNT
     *
     * @return the value of CUS_PERS.EU_RESIDNT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getEuResidnt() {
        return euResidnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.EU_RESIDNT
     *
     * @param euResidnt the value for CUS_PERS.EU_RESIDNT
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setEuResidnt(String euResidnt) {
        this.euResidnt = euResidnt == null ? null : euResidnt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.IP_ADDRESS
     *
     * @return the value of CUS_PERS.IP_ADDRESS
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.IP_ADDRESS
     *
     * @param ipAddress the value for CUS_PERS.IP_ADDRESS
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.UUID
     *
     * @return the value of CUS_PERS.UUID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.UUID
     *
     * @param uuid the value for CUS_PERS.UUID
     *
     * @mbggenerated Mon Nov 18 17:43:31 IST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }
    
    /**
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.EMAIL_VERIFIED
     *
     * @return the value of CUS_PERS.EMAIL_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public String getEmailVerified() {
        return emailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.EMAIL_VERIFIED
     *
     * @param emailVerified the value for CUS_PERS.EMAIL_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public void setEmailVerified(String emailVerified) {
        this.emailVerified = emailVerified == null ? null : emailVerified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.MOBILE_VERIFIED
     *
     * @return the value of CUS_PERS.MOBILE_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public String getMobileVerified() {
        return mobileVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.MOBILE_VERIFIED
     *
     * @param mobileVerified the value for CUS_PERS.MOBILE_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public void setMobileVerified(String mobileVerified) {
        this.mobileVerified = mobileVerified == null ? null : mobileVerified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.LAST_EMAIL_VERIFIED
     *
     * @return the value of CUS_PERS.LAST_EMAIL_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public Date getLastEmailVerified() {
        return lastEmailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.LAST_EMAIL_VERIFIED
     *
     * @param lastEmailVerified the value for CUS_PERS.LAST_EMAIL_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public void setLastEmailVerified(Date lastEmailVerified) {
        this.lastEmailVerified = lastEmailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PERS.LAST_MOBILE_VERIFIED
     *
     * @return the value of CUS_PERS.LAST_MOBILE_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public Date getLastMobileVerified() {
        return lastMobileVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PERS.LAST_MOBILE_VERIFIED
     *
     * @param lastMobileVerified the value for CUS_PERS.LAST_MOBILE_VERIFIED
     *
     * @mbggenerated Tue Dec 29 15:41:22 IST 2020
     */
    public void setLastMobileVerified(Date lastMobileVerified) {
        this.lastMobileVerified = lastMobileVerified;
    }
}