package MARMSUI.migration.model;

public class CusPinKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PIN.INT_ID
     *
     * @mbggenerated Wed Oct 23 11:26:58 IST 2019
     */
    private Long intId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PIN.PRG_CD
     *
     * @mbggenerated Wed Oct 23 11:26:58 IST 2019
     */
    private String prgCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PIN.INT_ID
     *
     * @return the value of CUS_PIN.INT_ID
     *
     * @mbggenerated Wed Oct 23 11:26:58 IST 2019
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PIN.INT_ID
     *
     * @param intId the value for CUS_PIN.INT_ID
     *
     * @mbggenerated Wed Oct 23 11:26:58 IST 2019
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PIN.PRG_CD
     *
     * @return the value of CUS_PIN.PRG_CD
     *
     * @mbggenerated Wed Oct 23 11:26:58 IST 2019
     */
    public String getPrgCd() {
        return prgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PIN.PRG_CD
     *
     * @param prgCd the value for CUS_PIN.PRG_CD
     *
     * @mbggenerated Wed Oct 23 11:26:58 IST 2019
     */
    public void setPrgCd(String prgCd) {
        this.prgCd = prgCd == null ? null : prgCd.trim();
    }
}