package MARMSUI.migration.model;

import java.math.BigDecimal;
import java.util.Date;

public class CusPrtSubprg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.RCRE_USER_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private String rcreUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.RCRE_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private Date rcreDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.LCHG_USER_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private String lchgUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.LCHG_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private Date lchgDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.INT_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private Long intId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SUBPRG_CD
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private String subprgCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SUBPRG_START_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private Date subprgStartDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.CUMULATIVE_SPEND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private BigDecimal cumulativeSpend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SHORTFALL
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private BigDecimal shortfall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SUBPRG_TIER
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private String subprgTier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SUBPRG_TIER_START_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private Date subprgTierStartDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SUBPRG_TIER_END_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private Date subprgTierEndDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SHIPPING_ADDR_IND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private String shippingAddrInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.BILLING_ADDR_IND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private String billingAddrInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.LIFE_CUMULATIVE_SPEND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private BigDecimal lifeCumulativeSpend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.KF_STATUS_MATCH
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private String kfStatusMatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUS_PRT_SUBPRG.SUBPRG_END_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    private Date subprgEndDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.RCRE_USER_ID
     *
     * @return the value of CUS_PRT_SUBPRG.RCRE_USER_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public String getRcreUserId() {
        return rcreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.RCRE_USER_ID
     *
     * @param rcreUserId the value for CUS_PRT_SUBPRG.RCRE_USER_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId == null ? null : rcreUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.RCRE_DT
     *
     * @return the value of CUS_PRT_SUBPRG.RCRE_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public Date getRcreDt() {
        return rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.RCRE_DT
     *
     * @param rcreDt the value for CUS_PRT_SUBPRG.RCRE_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setRcreDt(Date rcreDt) {
        this.rcreDt = rcreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.LCHG_USER_ID
     *
     * @return the value of CUS_PRT_SUBPRG.LCHG_USER_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public String getLchgUserId() {
        return lchgUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.LCHG_USER_ID
     *
     * @param lchgUserId the value for CUS_PRT_SUBPRG.LCHG_USER_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId == null ? null : lchgUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.LCHG_DT
     *
     * @return the value of CUS_PRT_SUBPRG.LCHG_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public Date getLchgDt() {
        return lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.LCHG_DT
     *
     * @param lchgDt the value for CUS_PRT_SUBPRG.LCHG_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setLchgDt(Date lchgDt) {
        this.lchgDt = lchgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.INT_ID
     *
     * @return the value of CUS_PRT_SUBPRG.INT_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public Long getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.INT_ID
     *
     * @param intId the value for CUS_PRT_SUBPRG.INT_ID
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SUBPRG_CD
     *
     * @return the value of CUS_PRT_SUBPRG.SUBPRG_CD
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public String getSubprgCd() {
        return subprgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SUBPRG_CD
     *
     * @param subprgCd the value for CUS_PRT_SUBPRG.SUBPRG_CD
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setSubprgCd(String subprgCd) {
        this.subprgCd = subprgCd == null ? null : subprgCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SUBPRG_START_DT
     *
     * @return the value of CUS_PRT_SUBPRG.SUBPRG_START_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public Date getSubprgStartDt() {
        return subprgStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SUBPRG_START_DT
     *
     * @param subprgStartDt the value for CUS_PRT_SUBPRG.SUBPRG_START_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setSubprgStartDt(Date subprgStartDt) {
        this.subprgStartDt = subprgStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.CUMULATIVE_SPEND
     *
     * @return the value of CUS_PRT_SUBPRG.CUMULATIVE_SPEND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public BigDecimal getCumulativeSpend() {
        return cumulativeSpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.CUMULATIVE_SPEND
     *
     * @param cumulativeSpend the value for CUS_PRT_SUBPRG.CUMULATIVE_SPEND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setCumulativeSpend(BigDecimal cumulativeSpend) {
        this.cumulativeSpend = cumulativeSpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SHORTFALL
     *
     * @return the value of CUS_PRT_SUBPRG.SHORTFALL
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public BigDecimal getShortfall() {
        return shortfall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SHORTFALL
     *
     * @param shortfall the value for CUS_PRT_SUBPRG.SHORTFALL
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setShortfall(BigDecimal shortfall) {
        this.shortfall = shortfall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SUBPRG_TIER
     *
     * @return the value of CUS_PRT_SUBPRG.SUBPRG_TIER
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public String getSubprgTier() {
        return subprgTier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SUBPRG_TIER
     *
     * @param subprgTier the value for CUS_PRT_SUBPRG.SUBPRG_TIER
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setSubprgTier(String subprgTier) {
        this.subprgTier = subprgTier == null ? null : subprgTier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SUBPRG_TIER_START_DT
     *
     * @return the value of CUS_PRT_SUBPRG.SUBPRG_TIER_START_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public Date getSubprgTierStartDt() {
        return subprgTierStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SUBPRG_TIER_START_DT
     *
     * @param subprgTierStartDt the value for CUS_PRT_SUBPRG.SUBPRG_TIER_START_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setSubprgTierStartDt(Date subprgTierStartDt) {
        this.subprgTierStartDt = subprgTierStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SUBPRG_TIER_END_DT
     *
     * @return the value of CUS_PRT_SUBPRG.SUBPRG_TIER_END_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public Date getSubprgTierEndDt() {
        return subprgTierEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SUBPRG_TIER_END_DT
     *
     * @param subprgTierEndDt the value for CUS_PRT_SUBPRG.SUBPRG_TIER_END_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setSubprgTierEndDt(Date subprgTierEndDt) {
        this.subprgTierEndDt = subprgTierEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SHIPPING_ADDR_IND
     *
     * @return the value of CUS_PRT_SUBPRG.SHIPPING_ADDR_IND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public String getShippingAddrInd() {
        return shippingAddrInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SHIPPING_ADDR_IND
     *
     * @param shippingAddrInd the value for CUS_PRT_SUBPRG.SHIPPING_ADDR_IND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setShippingAddrInd(String shippingAddrInd) {
        this.shippingAddrInd = shippingAddrInd == null ? null : shippingAddrInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.BILLING_ADDR_IND
     *
     * @return the value of CUS_PRT_SUBPRG.BILLING_ADDR_IND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public String getBillingAddrInd() {
        return billingAddrInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.BILLING_ADDR_IND
     *
     * @param billingAddrInd the value for CUS_PRT_SUBPRG.BILLING_ADDR_IND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setBillingAddrInd(String billingAddrInd) {
        this.billingAddrInd = billingAddrInd == null ? null : billingAddrInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.LIFE_CUMULATIVE_SPEND
     *
     * @return the value of CUS_PRT_SUBPRG.LIFE_CUMULATIVE_SPEND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public BigDecimal getLifeCumulativeSpend() {
        return lifeCumulativeSpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.LIFE_CUMULATIVE_SPEND
     *
     * @param lifeCumulativeSpend the value for CUS_PRT_SUBPRG.LIFE_CUMULATIVE_SPEND
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setLifeCumulativeSpend(BigDecimal lifeCumulativeSpend) {
        this.lifeCumulativeSpend = lifeCumulativeSpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.KF_STATUS_MATCH
     *
     * @return the value of CUS_PRT_SUBPRG.KF_STATUS_MATCH
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public String getKfStatusMatch() {
        return kfStatusMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.KF_STATUS_MATCH
     *
     * @param kfStatusMatch the value for CUS_PRT_SUBPRG.KF_STATUS_MATCH
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setKfStatusMatch(String kfStatusMatch) {
        this.kfStatusMatch = kfStatusMatch == null ? null : kfStatusMatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUS_PRT_SUBPRG.SUBPRG_END_DT
     *
     * @return the value of CUS_PRT_SUBPRG.SUBPRG_END_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public Date getSubprgEndDt() {
        return subprgEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUS_PRT_SUBPRG.SUBPRG_END_DT
     *
     * @param subprgEndDt the value for CUS_PRT_SUBPRG.SUBPRG_END_DT
     *
     * @mbg.generated Thu Feb 17 10:21:13 IST 2022
     */
    public void setSubprgEndDt(Date subprgEndDt) {
        this.subprgEndDt = subprgEndDt;
    }
}