package MARMSUI.migration.model;

public class CusPhoneKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.INT_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private Long intId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.PHONE_TYPE
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String phoneType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.INT_ID
	 *
	 * @return the value of CUS_PHONE.INT_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public Long getIntId() {
		return intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.INT_ID
	 *
	 * @param intId the value for CUS_PHONE.INT_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setIntId(Long intId) {
		this.intId = intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.PHONE_TYPE
	 *
	 * @return the value of CUS_PHONE.PHONE_TYPE
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getPhoneType() {
		return phoneType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.PHONE_TYPE
	 *
	 * @param phoneType the value for CUS_PHONE.PHONE_TYPE
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType == null ? null : phoneType.trim();
	}
}