package MARMSUI.migration.model;

import java.util.Date;

public class CusPhone extends CusPhoneKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.RCRE_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String rcreUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.RCRE_DT
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private Date rcreDt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.LCHG_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String lchgUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.LCHG_DT
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private Date lchgDt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.PHONE_CTRY_CD
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String phoneCtryCd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.PHONE_AREA_CD
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String phoneAreaCd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.PHONE_NO
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String phoneNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.MOBILE_MSG_SVC_FLG
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String mobileMsgSvcFlg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.MOBILE_SVC_PROVIDER
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String mobileSvcProvider;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.MOBILE_SUBSC_NETW
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String mobileSubscNetw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.PAGER_SVC_TYPE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String pagerSvcTypeInd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.RCV_FLT_PAGING_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String rcvFltPagingInd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.MOBILE_RCV_FLT_PAGING_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String mobileRcvFltPagingInd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.PREF_PHONE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String prefPhoneInd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column CUS_PHONE.ALT_PHONE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	private String altPhoneInd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.RCRE_USER_ID
	 *
	 * @return the value of CUS_PHONE.RCRE_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getRcreUserId() {
		return rcreUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.RCRE_USER_ID
	 *
	 * @param rcreUserId the value for CUS_PHONE.RCRE_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setRcreUserId(String rcreUserId) {
		this.rcreUserId = rcreUserId == null ? null : rcreUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.RCRE_DT
	 *
	 * @return the value of CUS_PHONE.RCRE_DT
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public Date getRcreDt() {
		return rcreDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.RCRE_DT
	 *
	 * @param rcreDt the value for CUS_PHONE.RCRE_DT
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setRcreDt(Date rcreDt) {
		this.rcreDt = rcreDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.LCHG_USER_ID
	 *
	 * @return the value of CUS_PHONE.LCHG_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getLchgUserId() {
		return lchgUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.LCHG_USER_ID
	 *
	 * @param lchgUserId the value for CUS_PHONE.LCHG_USER_ID
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setLchgUserId(String lchgUserId) {
		this.lchgUserId = lchgUserId == null ? null : lchgUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.LCHG_DT
	 *
	 * @return the value of CUS_PHONE.LCHG_DT
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public Date getLchgDt() {
		return lchgDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.LCHG_DT
	 *
	 * @param lchgDt the value for CUS_PHONE.LCHG_DT
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setLchgDt(Date lchgDt) {
		this.lchgDt = lchgDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.PHONE_CTRY_CD
	 *
	 * @return the value of CUS_PHONE.PHONE_CTRY_CD
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getPhoneCtryCd() {
		return phoneCtryCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.PHONE_CTRY_CD
	 *
	 * @param phoneCtryCd the value for CUS_PHONE.PHONE_CTRY_CD
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setPhoneCtryCd(String phoneCtryCd) {
		this.phoneCtryCd = phoneCtryCd == null ? null : phoneCtryCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.PHONE_AREA_CD
	 *
	 * @return the value of CUS_PHONE.PHONE_AREA_CD
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getPhoneAreaCd() {
		return phoneAreaCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.PHONE_AREA_CD
	 *
	 * @param phoneAreaCd the value for CUS_PHONE.PHONE_AREA_CD
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setPhoneAreaCd(String phoneAreaCd) {
		this.phoneAreaCd = phoneAreaCd == null ? null : phoneAreaCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.PHONE_NO
	 *
	 * @return the value of CUS_PHONE.PHONE_NO
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getPhoneNo() {
		return phoneNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.PHONE_NO
	 *
	 * @param phoneNo the value for CUS_PHONE.PHONE_NO
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo == null ? null : phoneNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.MOBILE_MSG_SVC_FLG
	 *
	 * @return the value of CUS_PHONE.MOBILE_MSG_SVC_FLG
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getMobileMsgSvcFlg() {
		return mobileMsgSvcFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.MOBILE_MSG_SVC_FLG
	 *
	 * @param mobileMsgSvcFlg the value for CUS_PHONE.MOBILE_MSG_SVC_FLG
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setMobileMsgSvcFlg(String mobileMsgSvcFlg) {
		this.mobileMsgSvcFlg = mobileMsgSvcFlg == null ? null : mobileMsgSvcFlg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.MOBILE_SVC_PROVIDER
	 *
	 * @return the value of CUS_PHONE.MOBILE_SVC_PROVIDER
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getMobileSvcProvider() {
		return mobileSvcProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.MOBILE_SVC_PROVIDER
	 *
	 * @param mobileSvcProvider the value for CUS_PHONE.MOBILE_SVC_PROVIDER
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setMobileSvcProvider(String mobileSvcProvider) {
		this.mobileSvcProvider = mobileSvcProvider == null ? null : mobileSvcProvider.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.MOBILE_SUBSC_NETW
	 *
	 * @return the value of CUS_PHONE.MOBILE_SUBSC_NETW
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getMobileSubscNetw() {
		return mobileSubscNetw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.MOBILE_SUBSC_NETW
	 *
	 * @param mobileSubscNetw the value for CUS_PHONE.MOBILE_SUBSC_NETW
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setMobileSubscNetw(String mobileSubscNetw) {
		this.mobileSubscNetw = mobileSubscNetw == null ? null : mobileSubscNetw.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.PAGER_SVC_TYPE_IND
	 *
	 * @return the value of CUS_PHONE.PAGER_SVC_TYPE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getPagerSvcTypeInd() {
		return pagerSvcTypeInd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.PAGER_SVC_TYPE_IND
	 *
	 * @param pagerSvcTypeInd the value for CUS_PHONE.PAGER_SVC_TYPE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setPagerSvcTypeInd(String pagerSvcTypeInd) {
		this.pagerSvcTypeInd = pagerSvcTypeInd == null ? null : pagerSvcTypeInd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.RCV_FLT_PAGING_IND
	 *
	 * @return the value of CUS_PHONE.RCV_FLT_PAGING_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getRcvFltPagingInd() {
		return rcvFltPagingInd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.RCV_FLT_PAGING_IND
	 *
	 * @param rcvFltPagingInd the value for CUS_PHONE.RCV_FLT_PAGING_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setRcvFltPagingInd(String rcvFltPagingInd) {
		this.rcvFltPagingInd = rcvFltPagingInd == null ? null : rcvFltPagingInd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.MOBILE_RCV_FLT_PAGING_IND
	 *
	 * @return the value of CUS_PHONE.MOBILE_RCV_FLT_PAGING_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getMobileRcvFltPagingInd() {
		return mobileRcvFltPagingInd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.MOBILE_RCV_FLT_PAGING_IND
	 *
	 * @param mobileRcvFltPagingInd the value for
	 *                              CUS_PHONE.MOBILE_RCV_FLT_PAGING_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setMobileRcvFltPagingInd(String mobileRcvFltPagingInd) {
		this.mobileRcvFltPagingInd = mobileRcvFltPagingInd == null ? null : mobileRcvFltPagingInd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.PREF_PHONE_IND
	 *
	 * @return the value of CUS_PHONE.PREF_PHONE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getPrefPhoneInd() {
		return prefPhoneInd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.PREF_PHONE_IND
	 *
	 * @param prefPhoneInd the value for CUS_PHONE.PREF_PHONE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setPrefPhoneInd(String prefPhoneInd) {
		this.prefPhoneInd = prefPhoneInd == null ? null : prefPhoneInd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column CUS_PHONE.ALT_PHONE_IND
	 *
	 * @return the value of CUS_PHONE.ALT_PHONE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public String getAltPhoneInd() {
		return altPhoneInd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column CUS_PHONE.ALT_PHONE_IND
	 *
	 * @param altPhoneInd the value for CUS_PHONE.ALT_PHONE_IND
	 *
	 * @mbggenerated Mon Sep 24 10:31:52 IST 2018
	 */
	public void setAltPhoneInd(String altPhoneInd) {
		this.altPhoneInd = altPhoneInd == null ? null : altPhoneInd.trim();
	}
}